### ISSUE TITLE
自动导入函数的性能优化

### ISSUE THREAD

**Issue by killme2008** [killme2008/aviatorscript#158]
目前对于重载的方法会有性能的损耗，因为采用的是反射的方式，
理论上可以做一个 parameter 列表的 class 列表到 Method Handle 的映射，只要调用函数的参数类型相对固定，这个缓存可以极大的加速方法的查找，然后将 Method.invoke 替换为 MethodHandle.invoke，可以得到接近自定义函数实现的性能。

**Comment by killme2008** [comment]
做了一个版本的实现，反复做了性能测试，在 JDK8 上，性能的最大损耗不是反射，而是类型的 box/unbox 了，因此这个优化暂时没有价值。

**Comment by wilddylan** [comment]
目前有这个库的性能测试报告 给出来么？

比如执行一次耗时、编译耗时等
