### ISSUE TITLE
是否有提供获取所有方法信息的接口

### ISSUE THREAD

**Issue by bluecrush** [killme2008/aviatorscript#227]
想获得所有的方法名，参数个数

**Comment by killme2008** [comment]
这个选项是你想要的吗？
https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#CAPTURE_FUNCTION_ARGS

**Comment by killme2008** [comment]
v5.4.2 release https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.2
