### ISSUE TITLE
如何获取表达式中的“外部变量”

### ISSUE THREAD

**Issue by xiabobin** [killme2008/aviatorscript#277]
av脚本如下:
`let totalAmount= price * num;`
`return totalAmount;`
**需求：**
希望增加获取脚本内“入参”的API。如只返回例子中的price、num。

**应用场景：**
1.编译脚本，获取需要在execute执行传入的参数。如：price、num
2.应用层从数据库中获取price、num数值。
3.传入price、num数值execute脚本。

**问题**
1.现在通过`getVariableFullNames()`获取的参数集合是包含脚本内自定义的变量，这个变量的值不需要外部指定，也就不需要外部传入，是在execute时不关心的。
2.如果获取到脚本内的“成员变量”应用层就需要尝试的获取该变量的数值，因为“成员变量”是在应用层未定义的，业务层面会报错。
**相关问题** 
#202 

**最后**
我该在哪里改造才能应对这个需求呢？

**Comment by 1024BytesMore** [comment]
臣附议：
（Expression内部的词法解析可以做到内外部变量）
1、获取外部变量；
2、获取函数列表；[#227](https://github.com/killme2008/aviatorscript/issues/227)
在表达式计算的时候，特别是动态调整的时候需要。
目前，我们只能在计算之前，通过自定义的占位符进行解析来区分。

**Comment by 6768745e** [comment]
#202 似乎是没有完全解决，当时我看回复的是beta版本，所以没去尝试。后来用5.0后的release版本试了一下，似乎之前描述的问题还在。不知道是我使用方式问题或者现在release的版本还没有包含进去。

**Comment by jackieha** [comment]
我们也有完全相同的需求。 需要获取到外部变量来进行提前校验。

**Comment by killme2008** [comment]
在 5.2.2 版本会修正这个问题， getVariableFullNames() 和 getVariableNames 都将返回未初始化的全局变量。

**Comment by killme2008** [comment]
5.2.2 发布 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.2
