### ISSUE TITLE
实现类似excel的三元表达式功能

### ISSUE THREAD

**Issue by sky1983** [killme2008/aviatorscript#283]
请教一下，我现在希望实现一个类似excel的三元表达式功能，现在已经根据用户自定义是现实了功能，但是在测试的是否发现执行顺序并非按照框架提供的三元表达式方式在执行，一下为跟踪代码示例和跟踪代码，
`expression = "a == '真' ? 1 : b=='' ? 1 : 0";`
 `AviatorEvaluator.setOption(Options.TRACE_EVAL, true);`
` compiledExp = AviatorEvaluator.compile(expression);`
` Long result1 = (Long) compiledExp.execute(compiledExp.newEnv("a", "真", "b", ""));`
` System.out.println(result1);`

 ` AviatorEvaluator.addFunction(new IFFunction());`
`expression = "IF(a=='真',0,IF(b=='',1,0))";`
` compiledExp = AviatorEvaluator.compile(expression);`
` result1 = (Long) compiledExp.execute(compiledExp.newEnv("a", "真", "b", "假"));`
`System.out.println(result1);`

`[Aviator TRACE]          <JavaType, a, 真, java.lang.String> == <String, 真> => <Boolean, true>`
`[Aviator TRACE] Result : 1`
`[Aviator TRACE]          <JavaType, a, 真, java.lang.String> == <String, 真> => <Boolean, true>`
`[Aviator TRACE]          <JavaType, b, 假, java.lang.String> == <String, > => <Boolean, false>`
`[Aviator TRACE] Func   : IF(<Boolean, false>,<Long, 1>,<Long, 0>)`
`[Aviator TRACE] Result : <Long, 0>`
`[Aviator TRACE] Func   : IF(<Boolean, true>,<Long, 0>,<Long, 0>)`
`[Aviator TRACE] Result : <Long, 0>`
`[Aviator TRACE] Result : 0`
可以看到第一个用例在第一个结果为true之后后一个表达式就不再执行了，而我实现的在传递参数时会先将执行里层表达式再执行外层的表达式，请问如何能对执行过程进行排序。
谢谢

**Comment by killme2008** [comment]
方法的求值都是先对参数求值，才执行方法，并不支持所谓的正则序，建议直接使用语言内置的 if 表达式。
