### ISSUE TITLE
程序在AviatorEvaluator.getInstance().execute(expression, map)处阻塞

### ISSUE THREAD

**Issue by yh2388** [killme2008/aviatorscript#289]
Aviator版本 -  [5.0.1]

jdk版本 - [1.8.0_92]

而我在另外几个环境中 jdk版本1.8.0_181则可以正常执行， 在1.8.0_92的环境下， 程序执行到这个代码段就阻塞了， 后续的代码不再执行也没有异常抛出。

**Comment by killme2008** [comment]
有没有可复现的代码

**Comment by killme2008** [comment]
可以 jstack 看下阻塞在哪里

**Comment by yh2388** [comment]
> 可以 jstack 看下阻塞在哪里

时间原因， 没有做复现，直接升级了jdk
