### ISSUE TITLE
希望能补全math里的常用函数

### ISSUE THREAD

**Issue by Tancen** [killme2008/aviatorscript#290]
https://www.yuque.com/boyan-avfmj/aviatorscript/ashevw
目前实现的math函数非常少，包括常用的 asin, acos 等等都没有，希望后续能补上

**Comment by killme2008** [comment]
有兴趣可以参与贡献，实现并不复杂

**Comment by killme2008** [comment]
5.2 发布

https://www.yuque.com/boyan-avfmj/aviatorscript/bggwx2#hWQXh
