### ISSUE TITLE
Metaspace outOfmemory

### ISSUE THREAD

**Issue by mask-zpt** [killme2008/aviatorscript#293]

**Comment by mask-zpt** [comment]
oracle: jdk1.8.0_121  
java.lang.OutOfMemoryError: Compressed class space
aviator version: 5.1.4
cached when compile: true
cached when execute: true

![image](https://user-images.githubusercontent.com/4207801/93729123-b75b6180-fbf5-11ea-9ca3-79ee38c24cca.png)

**Comment by killme2008** [comment]
反馈不是这么反馈，没有背景，没有上下文，连文字都舍不得写一下，无从解答
