### ISSUE TITLE
compressed class space溢出

### ISSUE THREAD

**Issue by icevb6** [killme2008/aviatorscript#294]
帮分析一下

![111](https://user-images.githubusercontent.com/12793851/93857270-ed2f4180-fcec-11ea-9d1a-7d85ffd54cf6.png)

开始还是正常，运行一段时间后出现该问题。

以下是调用方式

![222](https://user-images.githubusercontent.com/12793851/93857763-adb52500-fced-11ea-9daf-758ced622909.png)

目前是不确定公式引擎的问题，还是其他问题引起该问题

**Comment by killme2008** [comment]
dump metaspace 看看吧，都是什么。

**Comment by killme2008** [comment]
你们的公式非常多吗？ 用的 jdk 版本是什么？ 为什么还用 classloader 的方式。

**Comment by icevb6** [comment]
嗯，循环调用。

**Comment by icevb6** [comment]
是不是没用缓存就不会出这样的问题？jdk 1.8.0_172
原来这样写的，每次会增加4k
 boolean flag = (boolean) AviatorEvaluator.execute(expression, env);
改成这样
boolean flag = (boolean) AviatorEvaluator.execute(expression, env, true);
问题得到了改造。

**Comment by icevb6** [comment]
是不是没用缓存就不会出这样的问题？jdk 1.8.0_172
原来这样写的，每次会增加4k
boolean flag = (boolean) AviatorEvaluator.execute(expression, env);
改成这样
boolean flag = (boolean) AviatorEvaluator.execute(expression, env, true);
问题得到了改善。

**Comment by killme2008** [comment]
compie(expression ,true) 也是启用了缓存的。

**Comment by killme2008** [comment]
你们应该是开了压缩指针，可以将 `-XX:CompressedClassSpaceSize` 增大看看。

**Comment by icevb6** [comment]
刚才描述有点问题，如果这样写，boolean flag = (boolean) AviatorEvaluator.execute(expression, env);好像是有问题。改成boolean flag = (boolean) AviatorEvaluator.execute(expression, env, true);问题好像得到了解决，麻烦帮确认一下，谢谢？

**Comment by killme2008** [comment]
你的贴图代码，和你现在的描述是对不上对， execute(expression, env, true) 也是启用缓存。具体见 FAQ https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#On0Pg

**Comment by icevb6** [comment]
嗯，写代码的同事没调用公有方法，后来发现的

**Comment by killme2008** [comment]
ok，我先关闭了
