### ISSUE TITLE
Sequence能否扩展支持Linq的语法

### ISSUE THREAD

**Issue by datastairs** [killme2008/aviatorscript#295]
Sequence能否支持复杂的lamda函数比如groupBy之类，或者支持Linq的语法支持加入select，where等支持。

**Comment by killme2008** [comment]
groupBy 完全可以自己实现，也很容易。

**Comment by killme2008** [comment]
类似 linkq 的语法，在考虑支持sql https://github.com/killme2008/aviatorscript/issues/240
