### ISSUE TITLE
对于参数为列表时表达式求值的疑问

### ISSUE THREAD

**Issue by kute** [killme2008/aviatorscript#299]
比如我有这样的一个表达式

```
(a > 1 && a < 10) || (b != 2 && b> 0)
```
然后 对于 变量 a, b 的值 目前有这样的情况：

```
Map<String, Object> map = ....

map.put("a", Lists.newArrayList(2, 3, 4, 5, 6, 7, 8, 9, 10));
map.put("b", Lists.newArrayList(1, 3, 4, 5, 6, 7, 8, 9, 10, 2));
```
那该如何 求值呢？

有没有一个直接的运算如  matchAll  、matchAny ? 

或者 提供个新的运算符 ：in  ，或者 可以 自定义新增运算符吗？不是重载

运算符重载？ 和遍历 a,b 的值去匹配更简单

**Comment by killme2008** [comment]
不是可以 for 吗？ https://www.yuque.com/boyan-avfmj/aviatorscript/vfqgqn

**Comment by killme2008** [comment]
不过用 seq.every 会更优雅一点

```js
seq.every(a, lambda(x) -> 
                          seq.every(b, lambda(y) -> (x > 1 && x < 10) || (y != 2 && y> 0) end)
                end)
```
函数列表 https://www.yuque.com/boyan-avfmj/aviatorscript/ashevw
建议认真阅读下文档， aviatorscript 是非常强大的。
