### ISSUE TITLE
请问如何直接将内部异常抛出？

### ISSUE THREAD

**Issue by missfmaster** [killme2008/aviatorscript#305]
进行表达式求值时，比如 a < 2，不小心将 a 设置成了 字符串“2”，而不是数字2，内部导致了异常，请问如何直接将此异常抛出？而不是开启追踪才能看到？
com.googlecode.aviator.exception.CompareNotSupportedException: Could not compare <Long, 2> with <JavaType, a, 2, java.lang.String>

**Comment by killme2008** [comment]
请给出可复现的例子

**Comment by missfmaster** [comment]
@killme2008 你本地肯定有可以运行的环境吧？我给你段代码，你看下：
```
        AviatorEvaluatorInstance aviator = AviatorEvaluator.getInstance();
	    
        //aviator.setOption(Options.TRACE_EVAL, true);
        
	    /*
	     * 相等比较，调用了带有 eq 的比较方法，异常时直接输出到了控制台
	     * 结果为false
	     * 除非打开TRACE_EVAL，不然看不到异常
	     */
        Expression expression = aviator.compile("a == 2");
        Map<String, Object> map = expression.newEnv("a", "2");
        Boolean r = (Boolean)expression.execute(map);
        System.out.println(r);
        
        /*
         * 大小比较，调用不带 eq 的比较方法，异常时抛出了异常
         */
        Expression expression1 = aviator.compile("a < 2");
        Map<String, Object> map1 = expression1.newEnv("a", "2");
        Boolean r1 = (Boolean)expression1.execute(map1);
        System.out.println(r1);
```
不是理解 eq 时为何要隐藏异常？项目中使用时，因为结果不对，查找了好久才找到这里，无法比较的异常被偷偷隐藏了。

**Comment by killme2008** [comment]
这个跟你一开始说的是不一样的吧， `==` 和 `!=` 两个操作符，如果类型不同，不抛出异常，直接返回 true/false。  比较运算符才会检测类型。

**Comment by killme2008** [comment]
这是符合预期的，我先关闭了。

**Comment by killme2008** [comment]
这个设计的原因是为了更好地支持各类高阶函数，比如 filter, include 等，因为 aviator 是动态类型， sequence 可能是包含多个类型的集合，类似下面的脚本希望能正常运行，而不是抛出异常：

```
include(tuple(1, "a", 2, "b"), 2);  ## 返回 true
```

**Comment by missfmaster** [comment]
哦哦，理解你的意思了。
但是，`==`时返回了false，`<`时抛出了异常，感觉还是不太舒服；
比如，同样是动态类型，在js中，"2" == 2 结果是 true，"2" < 2 结果是 false，在比较时使用自动转换类型处理的，感觉这个思路挺好。
