### ISSUE TITLE
@Function定义的函数不支持可变长参数类型.

### ISSUE THREAD

**Issue by BOFA1ex** [killme2008/aviatorscript#311]
```java
@Function     
public static void info(String message, Object... args){
         log.info(message, args);     
}
```

```java
Example:
log.info("hello {} {}", "aviator", "script");

Error:
Caused by: java.lang.IllegalArgumentException: No matching method info found taking 3 args
```

只能通过定义AbstractVariadicFunction函数类吗? 
想通过module形式引入相关函数比较合理..
`let log = acquire('log');`

**Comment by killme2008** [comment]
可以的，只是那个参数你需要用数组的方式，参考

https://www.yuque.com/boyan-avfmj/aviatorscript/xbdgg2#16243fbe

**Comment by BOFA1ex** [comment]
脚本需要变更为`log.info("hello {} {}", tuple("aviator","script"));`

**Comment by canfeng** [comment]
3.0之后可以继承这个类实现自定义可变函数 com.googlecode.aviator.runtime.function.AbstractVariadicFunction#variadicCall
