### ISSUE TITLE
5.2.0以上运行失败

### ISSUE THREAD

**Issue by yitengda** [killme2008/aviatorscript#321]
问题：
运行AviatorEvaluator.execute失败，提示如下图：
![image](https://user-images.githubusercontent.com/33883188/101111365-01a98780-3616-11eb-9b63-09098fb9ced2.png)
提示好像是aviator.av里的take_while函数解析失败，可能是入参pred解析失败。

**Comment by killme2008** [comment]
错误信息很明显了， ClassNotFound ，应该是 commons-beanutils 冲突了，检查你的 classpath

**Comment by yitengda** [comment]
commons-beanutils版本问题，5.2.1必须要1.9.4才行
