### ISSUE TITLE
5.0.1 up to 5.2.1 error

### ISSUE THREAD

**Issue by angeltping** [killme2008/aviatorscript#329]
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated

a项目依赖了aviator，a项目启动正常，
b项目依赖了a，b项目无法启动

**Comment by angeltping** [comment]
使用的jdk1.8

**Comment by killme2008** [comment]
需要详细的错误信息，猜测应该就是 commons-beantuils 版本冲突

**Comment by angeltping** [comment]
Can't assign value to exports.take_while

**Comment by angeltping** [comment]
![image](https://user-images.githubusercontent.com/49736952/102187291-c26d1780-3eee-11eb-9f66-e6851bd2b1a1.png)

**Comment by killme2008** [comment]
就不能打印下完整堆栈？

**Comment by angeltping** [comment]
没有其他堆栈信息，
现在有一个其他问题能咨询一下你吗？

com.googlecode.aviator.Expression 的方式是线程安全的吗
我在多线程环境缓存了这个表达式，然后执行，发现，执行后params，里面的参数有串线程的情况，



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 16:45
To: killme2008/aviatorscript
CC: angeltping; Author
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
就不能打印下完整堆栈？

**Comment by angeltping** [comment]
能加一下老师的qq，沟通方便点，不会骚扰你的。
我的qq就是48690326


48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 16:45
To: killme2008/aviatorscript
CC: angeltping; Author
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
就不能打印下完整堆栈？

**Comment by killme2008** [comment]
@angeltping 你写的逻辑是线程安全的，他就是线程安全的，串 params 理论上不可能，也没有听到过任何类似反馈。

**Comment by angeltping** [comment]
这个我在打一下我的日志，看执行前后map有那些变化，
我这边并发有点高，当然也可能是我的问题，我再核实一下



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 17:18
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
@angeltping 你写的逻辑是线程安全的，他就是线程安全的，串 params 理论上不可能，也没有听到过任何类似反馈。

**Comment by angeltping** [comment]
我想问的是，同一个表达式，多线程不通的参数调用，这样是线程安全的吗？


48690326@qq.com

From: dennis zhuang
Date: 2020-12-15 17:18
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
@angeltping 你写的逻辑是线程安全的，他就是线程安全的，串 params 理论上不可能，也没有听到过任何类似反馈。

**Comment by killme2008** [comment]
你这个启动异常应该跟这个一样

https://github.com/killme2008/aviatorscript/issues/331

**Comment by angeltping** [comment]
多谢，我在看看，应该是你说的问题。
串参数的那个是我自己的问题，我已经查到了。



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 17:49
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
你这个启动异常应该跟这个一样
#331

**Comment by angeltping** [comment]
这个是类引入了spring的webclient，就会出现
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated



这样就不会出现上面的spi无法加载的情况，感觉像是aviator和spring的webClient的什么东西有冲突




48690326@qq.com
 
From: 48690326@qq.com
Date: 2020-12-15 17:52
To: killme2008/aviatorscript
Subject: Re: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
多谢，我在看看，应该是你说的问题。
串参数的那个是我自己的问题，我已经查到了。



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 17:49
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
你这个启动异常应该跟这个一样
#331

**Comment by angeltping** [comment]
依赖是没有问题的


48690326@qq.com
 
From: 48690326@qq.com
Date: 2020-12-15 19:15
To: killme2008/aviatorscript
Subject: Re: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
这个是类引入了spring的webclient，就会出现
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated



这样就不会出现上面的spi无法加载的情况，感觉像是aviator和spring的webClient的什么东西有冲突




48690326@qq.com
 
From: 48690326@qq.com
Date: 2020-12-15 17:52
To: killme2008/aviatorscript
Subject: Re: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
多谢，我在看看，应该是你说的问题。
串参数的那个是我自己的问题，我已经查到了。



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 17:49
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
你这个启动异常应该跟这个一样
#331

**Comment by angeltping** [comment]
48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 17:49
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
Closed #329.

**Comment by angeltping** [comment]
我看5.0.1和5.2.1差别
5.2.1依赖包中有一个
我debug，从堆栈中就是这个句报出的异常，不知道这个是什么用的，这个aviator.av 文件的作用是什么
Can't assign value to exports.take_while
我项目中引用了groovy脚本引擎，不知道这个有影响不？


48690326@qq.com
 
发件人： 48690326@qq.com
发送时间： 2020-12-15 19:33
收件人： killme2008/aviatorscript
主题： Spring WebClient 也会使用到脚本引擎，应该是有什么冲突



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-15 17:49
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
Closed #329.

**Comment by killme2008** [comment]
前面都已经给你提示了，检查你的 classpath，肯定存在多个版本的 commons-beanutils，排除一个版本即可。

**Comment by angeltping** [comment]
<dependencies>
   <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
      <exclusions>
         <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
         </exclusion>
         <exclusion>
            <artifactId>commons-io</artifactId>
            <groupId>commons-io</groupId>
         </exclusion>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
      <exclusions>
         <exclusion>
            <artifactId>jsr305</artifactId>
            <groupId>com.google.code.findbugs</groupId>
         </exclusion>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>org.springframework.plugin</groupId>
      <artifactId>spring-plugin-core</artifactId>
      <version>${spring.plugin.version}</version>
      <exclusions>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>org.springframework.plugin</groupId>
      <artifactId>spring-plugin-metadata</artifactId>
      <version>${spring.plugin.version}</version>
      <exclusions>
         <exclusion>
            <artifactId>spring-plugin-core</artifactId>
            <groupId>org.springframework.plugin</groupId>
         </exclusion>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>${mysql.version}</version>
      <exclusions>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>
   
   <dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams</artifactId>
      <version>${reactive-streams.version}</version>
      <exclusions>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>
   
   <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>${reactor-core.version}</version>
      <exclusions>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>
   
   <dependency>
      <groupId>com.crunii.workflow</groupId>
      <artifactId>wf-base</artifactId>
      <exclusions>
         <exclusion>
            <artifactId>spring-plugin-metadata</artifactId>
            <groupId>org.springframework.plugin</groupId>
         </exclusion>
         <exclusion>
            <artifactId>reactor-core</artifactId>
            <groupId>io.projectreactor</groupId>
         </exclusion>
         <exclusion>
            <artifactId>spring-plugin-core</artifactId>
            <groupId>org.springframework.plugin</groupId>
         </exclusion>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>com.hazelcast</groupId>
      <artifactId>hazelcast</artifactId>
      <version>4.1</version>
      <exclusions>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>com.hazelcast</groupId>
      <artifactId>hazelcast-kubernetes</artifactId>
      <version>2.2.1</version>
      <exclusions>
         <exclusion>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
         </exclusion>
      </exclusions>
   </dependency>

   <dependency>
      <groupId>commons-beanutils</groupId>
      <artifactId>commons-beanutils</artifactId>
      <version>1.9.4</version>
   </dependency>
   
</dependencies>



这个是eclipse里面的iml文件，没有多个版本只有1.9.4
我已经把项目所有的依赖排除了common-utils，
然后直接添加了依赖，不存在多个版本的问题

48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-16 10:31
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
前面都已经给你提示了，检查你的 classpath，肯定存在多个版本的 commons-beanutils，排除一个版本即可。

**Comment by killme2008** [comment]
有个东西叫间接依赖 mvn dependency:tree，我觉的这种东西自己去  google 就好，我不负责解答这种基本问题的。

**Comment by angeltping** [comment]
老师你好第一我mvn的这些基础命令我肯定会，也试过了，存在多版本的common-beanutils
第二出现上面问题的原因是依赖冲突的问题
这是我创建的一个最简单的项目，使用log4j2，在webflux不排除spring-jcl的情况就会出现
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated
无法实例化，当排除spring-jcl的时候就完全正常没有无法实例化，
我觉得aviator不应该和spring的这个jcl有冲突，不知道我理解对不，不知道这个算不算一个bug，或者就是必须要排除spring-jcl
还请老师指教。



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-16 10:48
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
有个东西叫间接依赖 mvn dependency:tree，我觉的这种东西自己去 google 就好，我不负责解答这种基本问题的。

**Comment by angeltping** [comment]
老师你好第一我mvn的这些基础命令我肯定会，也试过了，不存在多版本的common-beanutils
第二出现上面问题的原因是依赖冲突的问题
这是我创建的一个最简单的项目，使用log4j2，在webflux不排除spring-jcl的情况就会出现
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated
无法实例化，当排除spring-jcl的时候就完全正常没有无法实例化，
我觉得aviator不应该和spring的这个jcl有冲突，不知道我理解对不，不知道这个算不算一个bug，或者就是必须要排除spring-jcl
还请老师指教。



48690326@qq.com
 
From: dennis zhuang
Date: 2020-12-16 10:48
To: killme2008/aviatorscript
CC: angeltping; Mention
Subject: Re: [killme2008/aviatorscript] 5.0.1 up to 5.2.1 error (#329)
有个东西叫间接依赖 mvn dependency:tree，我觉的这种东西自己去 google 就好，我不负责解答这种基本问题的。
