### ISSUE TITLE
关于表达式缓存的使用优化（避免一些Surprise的感觉）

### ISSUE THREAD

**Issue by oldratlee** [killme2008/aviatorscript#330]
下面的使用方式有 Surprise的感觉：

- 调用了`AviatorEvaluatorInstance`的`useLRUExpressionCache`（`use*ExpressionCache`）方法，
    但不会生效表达式缓存，有些surprise。
- 还需要在执行（类`execute`方法）时，传递上`cached`参数为`true`，才生效表达式缓存。
    - 在执行时，设置『表达式是否缓存』，更显意，是好的。 :")
    - 在执行时，感觉可能有些繁琐； 因为执行方法可能会在不同地方多次执行。
    - 如果『表达式是否缓存』能在`AviatorEvaluatorInstance`上有个缺省设置：
        - 可以避免上面的『感觉繁琐』
        - 执行时的『表达式是否缓存』设置，可以显意覆盖`AviatorEvaluatorInstance`级的设置。
- 详见下面的show case代码。

上面可能问题的解决方法（`API`设计）是不是 可以下面的做法：

1. 在`AviatorEvaluatorInstance`级，可以（缺省）设置『表达式是否缓存』
1. `useLRUExpressionCache`/`use*ExpressionCache` 方法，隐含了`AviatorEvaluatorInstance`级『表达式要缓存』
    - 顾名思意，符合方法命名（`use*ExpressionCache`）的直觉，没有Surprise。
    - 这里要注意，**_向后兼容_** 的问题。
1. 考虑`AviatorEvaluatorInstance`级默认开启『表达式要缓存』？ @killme2008 
    - 对于大流量线上产品，动态编译出来的`Class`回收慢会压跨应用。
    - 但默认开启如何设置缓存大小是个难题？😂
    - 有 **_向后兼容_** 的问题

如果上面的思路/解决方法觉得OK，我可以试着给个PR。:")

--------------------

```java
public class ExpressionCacheBehaviorSurpriseTest {
    @Test
    public void call_useLRUExpressionCache_butExpressionNotCached__SURPRISE() {
        final Map<String, Object> context = new HashMap<>();
        context.put("var1", 10);
        context.put("var2", 20);
        final String expr = "var1 < 100 && var2 < 200";

        // --> Have called *use*LRUExpressionCache
        final AviatorEvaluatorInstance instance =
                AviatorEvaluator.newInstance().useLRUExpressionCache(100);
        final Boolean result = (Boolean) instance.execute(expr, context);
        assertTrue(result);
        // --> But expression Not cached. SURPRISE!
        assertFalse(instance.isExpressionCached(expr));
    }

    @Test
    public void shouldCall_useLRUExpressionCache_and_passCachedParameterToExecute_then_ExpressionWillCache() {
        final Map<String, Object> context = new HashMap<>();
        context.put("var1", 10);
        context.put("var2", 20);
        final String expr = "var1 < 100 && var2 < 200";

        // --> Have called *use*LRUExpressionCache
        final AviatorEvaluatorInstance instance =
                AviatorEvaluator.newInstance().useLRUExpressionCache(100);
        // --> And pass cached parameter to execute method
        final Boolean result = (Boolean) instance.execute(expr, context, true);
        assertTrue(result);
        // --> Then expression will cache
        assertTrue(instance.isExpressionCached(expr));
    }
}
```

PS: [show case source file](https://github.com/oldratlee/aviatorscript/blob/7da3bd0ec13e8d3881ddaec93b79c5ea78d400c7/src/test/java/surprise/ExpressionCacheBehaviorSurpriseTest.java#L15-L28)

### 相关资料

- Aviator官方文档：[最佳实践 - 使用编译缓存模式](https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#On0Pg) 
     - AviatorEvaluatorInstance#execute 时设置 cached参数为 true
     - 可以设置使用 LRU Cache

**Comment by killme2008** [comment]
最终决定引入一个属性，类似 `AviatorEvaluatorInstance#setExpressionCaching(boolean)` 来设置是否开启全局缓存。

**Comment by killme2008** [comment]
5.2.2 发布 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.2

**Comment by accfcx** [comment]
使用优化模式，避免重复编译以及GC等问题。但又面临另外一种需求：条件表达式没有变化，走优化路线；条件表达式有变化时，重新编译一遍，后面的执行还是走优化。

实际场景是应用启动时，从数据库加载脚本，执行请求时，按照编译优化。但同时定时服务获取数据库中的最新脚本，能够走新的脚本。请问这种该怎么用或者配置？
