### ISSUE TITLE
5.2.1->ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated

### ISSUE THREAD

**Issue by 13996280848** [killme2008/aviatorscript#333]
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.googlecode.aviator.script.AviatorScriptEngineFactory could not be instantiated

在使用spring框架的时候，如果不排除Jakarta Commons Logging，就会无法实例化aviator，System.error输出如上错误
<exclusion>
<groupId>org.springframework</groupId>
<artifactId>spring-jcl</artifactId>
</exclusion>

这问题能优化适配一下吗，不然很多地方需要排除这个spring-jcl的依赖

**Comment by killme2008** [comment]
跟这个框架一点关系也没有，自行研究吧。 aviator 唯一依赖就是 commons-beanutils。

https://github.com/killme2008/aviatorscript/blob/master/pom.xml
