### ISSUE TITLE
在安卓环境下使用内置函数报错

### ISSUE THREAD

**Issue by wangzhiqinzero** [killme2008/aviatorscript#334]
作者您好，我在安卓环境下使用Aviator的内置函数执行异常，代码如下：
`     String expression = "math.sqrt(4)";
      Object res = AviatorEvaluator.execute(expression);`
产生了如下异常：
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
请问这个问题现在有办法解决吗

**Comment by killme2008** [comment]
android 还是不支持。

**Comment by killme2008** [comment]
已支持解释模式，发布了 5.3.0-beta 版本，欢迎测试 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.3.0-beta

例子 https://github.com/killme2008/aviatorscript/blob/master/src/test/java/com/googlecode/aviator/example/InterpreterExample.java
文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ok8agx
