### ISSUE TITLE
关于script脚本中入参变量设别的疑问

### ISSUE THREAD

**Issue by bluecrush** [killme2008/aviatorscript#335]
1.目前在编译阶段，获取脚本入参变量，无法获取到局部代码块中引用但未定义的全局变量；
2.获取得到的变量中包含已经在全局变量中定义的变量，这些变量在外部赋值是无意义的；
![image](https://user-images.githubusercontent.com/24454904/103122316-a588cf00-46ba-11eb-963c-74e808bf655c.png)
![image](https://user-images.githubusercontent.com/24454904/103122312-a02b8480-46ba-11eb-9f6e-2aaab5c0c90b.png)

**Comment by killme2008** [comment]
5.2.2 发布 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.2

**Comment by bluecrush** [comment]
3Q


| |
BlueCrush
|
|
bluecrush@163.com
|
签名由网易邮箱大师定制


在2021年01月4日 18:07，dennis zhuang<notifications@github.com> 写道：

5.2.2 发布 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.2
