### ISSUE TITLE
compile lexeme `appModuleCode` without caching

### ISSUE THREAD

**Issue by iamsxm** [killme2008/aviatorscript#336]
你好，我在java自定义了一个函数，大概是通过调用外部api判断返回结果，但是在我获取参数的时候，提示compile lexeme `sei-rule` without caching

>  /**
>      * 访问外部服务，实现对环境参数自定义规则判断和修改
>      *
>      * @param env 环境参数
>      * @return Boolean 是否匹配成功
>      */
>     @Override
>     @SuppressWarnings("unchecked")
>     public AviatorObject call(Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
>         String appModuleCode = arg1.stringValue(env);
>         if (StringUtils.isEmpty(appModuleCode)) {
>             //00002 = 访问外部服务模块代码不能为空！
>             throw new ServiceException(ContextUtil.getMessage("00002"));
>         }
> }

String appModuleCode = arg1.stringValue(env);
这一步报错，下面是我的测试类

>     @Test
>     public void testMatchRuleComparatorFunction() {
>         String expression = "MatchRuleComparator('sei-rule','demoHello/matchRuleComparator')";
>         // 编译表达式
>         Expression compiledExp = AviatorEvaluator.compile(expression, true);
>         Map<String, Object> env = new HashMap<>();
>         env.put("a", 100.3);
>         env.put("b", 25);
>         //env.put("appModuleCode", "sei-rule");
>         //env.put("path", "demoHello/matchRuleComparator");
>         // 执行表达式
>         Boolean result = (Boolean) compiledExp.execute(env);
>         System.out.println(result);
>         Assert.assertTrue(result);
>     }

**Comment by killme2008** [comment]
升级到 5.2.1 版本

**Comment by killme2008** [comment]
用 getValue ，不要直接用 stringValue

**Comment by iamsxm** [comment]
> 用 getValue ，不要直接用 stringValue

依赖的是5.2.1版本，试了下getVaule，改用了官方的写法FunctionUtils.getStringValue(arg1, env); 
直接运行junit没提示，但是debug模式下运行junit会提示，我先关闭了吧。感谢大神回复！

**Comment by killme2008** [comment]
那个只是一个 warn，不会影响正确性，但是会对性能造成影响。
