### ISSUE TITLE
seq.set include 类型问题

### ISSUE THREAD

**Issue by luojian9508** [killme2008/aviatorscript#339]
public static void main(String[] args) {
        Map<String, Object> data = new HashMap<>();
        data.put("v1", 1); // Integer
        data.put("v2", 1L); // Long

        // set include
        String expression1 =
                "let set = seq.set(1, 2); " +
                "println(type(v1)); " + // long
                "println(type(v2)); " + // long
                "println(include(set, v1)); " + // false，与预期不一致
                "println(include(set, long(v1))); " + // true
                "println(include(set, v2));"; // true
        AviatorEvaluator.validate(expression1);
        Expression compiledExp1 = AviatorEvaluator.compile(expression1);
        compiledExp1.execute(data);

        // array include
        String expression2 =
                "let arr = seq.array(long, 1, 2); " +
                "println(type(v1)); " + // long
                "println(type(v2)); " + // long
                "println(include(arr, v1)); " + // true
                "println(include(arr, long(v1))); " + // true
                "println(include(arr, v2));"; // true
        AviatorEvaluator.validate(expression2);
        Expression compiledExp2 = AviatorEvaluator.compile(expression2);
        compiledExp2.execute(data);
    }

aviator 包版本：5.1.4

expression1，**采用set**，在脚本里都是v1和v2都是long类型，但是include(set, v1)输出的是false，**与预期不一致**
expression2，采用array，与预期一致
请问是什么原因呢？
@killme2008

**Comment by killme2008** [comment]
这是因为 include 针对 Set 类型会使用它的 contains 方法，做到 O(1) 的时间复杂度，这样就不会帮你做类型转换。而 array 会遍历循环， aviatorscript 会对相等检测调用内部规则。
