### ISSUE TITLE
执行表达式报空指针异常

### ISSUE THREAD

**Issue by waliccc** [killme2008/aviatorscript#341]
版本：5.2.2
当表达式取值为数组或者集合的某一个元素时，若该集合为null，则会抛出NullPointerException，例子：
```
Map<String, Object> map = new HashMap<>();
map.put("a", 1);
Expression expressionA = AviatorEvaluator.compile("a");
System.out.println(expressionA.execute(map));
Expression expressionB = AviatorEvaluator.compile("b");
System.out.println(expressionB.execute(map));
Expression expressionB0 = AviatorEvaluator.compile("b[0]");
System.out.println(expressionB0.execute(map));
```
最后一个表达式执行是否应该返回null才合理？实际使用时我们可能并不知道这个b是否会有值。
调试时发现 AviatorJavaType#getElement 方法在```Object thisValue = getValue(env);```时已经返回了null，但并未对该值做null的校验而直接使用了导致抛出 NullPointerException

**Comment by killme2008** [comment]
这个是预期的返回结果，如果你要返回 null，请启用 `Options.NIL_WHEN_PROPERTY_NOT_FOUND`，或者在使用前加一个判断 `! = nil` 判断。
