### ISSUE TITLE
有关nil比较的一点疑问

### ISSUE THREAD

**Issue by Alexmumu** [killme2008/aviatorscript#342]
目前看到是任何数与nil比较，都大于nil，这种个人认为是不是有些违反直觉，任何数与nil比较都返回false是不是更符合直觉一点呢？

**Comment by killme2008** [comment]
nil 表示空无一物，其他任何东西（除了nil自身）都比这个大，我觉的也挺好理解，现有规则，不适合改了。

**Comment by Alexmumu** [comment]
仅对nil补充一点个人观点，与这里是否改动无关的。
如果说nil表示空无一物，那么我理解的空无一物实则是一个零的概念，其与负数比较还是应该大于的；
而对于nil是否表示空无一物，个人认为将其解释为未知更为妥帖，因为未知，故所有问题都只能回答不是。
可能有点抬杠，可能基于对概念上的一点执念，还是想说出来，如有冒犯，还请见谅。
