### ISSUE TITLE
支持多行字符串

### ISSUE THREAD

**Issue by huanyunz** [killme2008/aviatorscript#343]
let s='''
         hello
         word
''';
let t="""
      hello
      word
"""

**Comment by killme2008** [comment]
不需要特殊语法，本来就支持

```
let s = "
hello
world
";

```

**Comment by huanyunz** [comment]
多行字符串，不是都在一行的，参考Python等编程语言

**Comment by killme2008** [comment]
@huanyunz 你打印我上面我的例子，他就是多行的。但是目前不支持转义多行到一行。
