### ISSUE TITLE
怎么调用java中自定义类的方法

### ISSUE THREAD

**Issue by klnhongye** [killme2008/aviatorscript#344]
调用接口实现类的方法
通过 AviatorEvaluator.addInstanceFunctions("ins", TestServiceImpl.class);
ins.test(TestServiceImpl.class, 'cs')
这样试过不行呢

**Comment by killme2008** [comment]
这样能行才怪了，认真读下文档吧

https://www.yuque.com/boyan-avfmj/aviatorscript/xbdgg2#103df912
