### ISSUE TITLE
include(set,num)使用的一点问题

### ISSUE THREAD

**Issue by Alexmumu** [killme2008/aviatorscript#345]
Set<Integer> set = new HashSet<>();
        set.add(3);
        set.add(20);
        set.add(10);
        env.put("set", set);
        Object result = AviatorEvaluator.execute("include(set,10)", env);
        System.out.println(result);//false
        System.out.println(AviatorEvaluator.execute("include(seq.list(10,3,4),10)"));//true

这里在传入set时，是不是自动将set和值的类型统一会比较好？ （否则就会直觉上我分明是int和int做包含判断，结果却是不包含）

**Comment by killme2008** [comment]
你传入的变量，不会做任何修改，你需要自己保证传入的变量和 aviator 类型的兼容性。
