### ISSUE TITLE
为什么表达式写的a<0，变量什么都没有传，表达式返回true？

### ISSUE THREAD

**Issue by 328060173** [killme2008/aviatorscript#347]
Map<String,Object> map=Maps.newHashMap();
        String expression=" a < 10 ";
        Expression compiledExp = AviatorEvaluator.compile(expression, true); 
//打印为什么是true？？？
        System.out.println( compiledExp.execute(map));

**Comment by killme2008** [comment]
仔细阅读文档，任何值都比 nil(null) 大，除了 nil 本身。
