### ISSUE TITLE
为什么获取表达式的变量时候会把true和false当成变量返回到List？

### ISSUE THREAD

**Issue by 328060173** [killme2008/aviatorscript#348]
String expression=" a == true ";
        Expression compiledExp = AviatorEvaluator.compile(expression, true);
//为什么打印：{a,true}，不应该只打印出来{a}么？true也是变量？
        compiledExp.getVariableFullNames().stream().forEach(a-> System.out.println(a));

**Comment by killme2008** [comment]
请升级到 5.2.2
