### ISSUE TITLE
使用Shell功能的时候，我想引用第三方jar，如hutool，然后在脚本中使用这些函数该怎么做

### ISSUE THREAD

**Issue by BleethNie** [killme2008/aviatorscript#355]
脚本中引用第三方jar时，执行脚本报错
![image](https://user-images.githubusercontent.com/17614992/106693337-35eaf580-6611-11eb-94e1-8b2ca727894c.png)

脚本源码
![image](https://user-images.githubusercontent.com/17614992/106693398-53b85a80-6611-11eb-8d5a-04dc334fb05a.png)

添加第三方jar位置（将jar放到和aviator-5.2.3.jar相同的位置）
![image](https://user-images.githubusercontent.com/17614992/106693421-60d54980-6611-11eb-85df-e75fc0edd2d6.png)

不知道具体的使用方法，在此请教作者

**Comment by killme2008** [comment]
需要制定  classpath:

`export CLASSPATH=xxxx; aviator test.av`

后面我会加个默认的 classpath 进去，只要放到那个目录即可，感谢建议

**Comment by killme2008** [comment]
发布了 5.2.4，支持 `AVITOR_DEPS` 环境变量来指定，默认是 `$HOME/.aviatorscript/deps`  目录
https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.4
