### ISSUE TITLE
怎么输出完整的表达式

### ISSUE THREAD

**Issue by BarryYang1** [killme2008/aviatorscript#358]
`AviatorEvaluatorInstance evaluatorInstance = AviatorEvaluator.getInstance();

Expression expression= evaluatorInstance.compile("a*100+b", true);

Map<String,Object> m = new HashMap<>();

m.put("a",1);

m.put("b",50);

int p = (Integer) expression.execute(m);
`
我想输出表达式嵌入参数的字符串，上面的输出”1*100+50“，这样的方法有吗

**Comment by jackieha** [comment]
evaluatorInstance.compile("a + '*100+' + b", true);

**Comment by killme2008** [comment]
可以用字符串插值

`"{a}*100+#{b}"`
