### ISSUE TITLE
嵌套对象中列表元素使用语法糖报错

### ISSUE THREAD

**Issue by hustfly** [killme2008/aviatorscript#364]
使用中发现一处报错：
例：
对象a的定义如下：
Class A {
      List<B> b;
} a
Class B {
      C c;
} b
表达式a.b[0]返回正常，是B对象，但是a.b[0].c 尝试获取对象b的属性c时报错。
报错内容：com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: unexpect token '.', maybe forget to insert ';' to complete last expression  at 166, lineNumber: 1, token : [type='Char',lexeme='.',index=166],
while parsing expression: 
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1488)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1449)

**Comment by killme2008** [comment]
使用 quote var `#a.b[0].c `

**Comment by hustfly** [comment]
> 使用 quote var `#a.b[0].c `

`#a.b[1+1].c ` 这样的不支持吗

**Comment by killme2008** [comment]
暂时不能，文档里都有说明，可以考虑在下个版本支持下
