### ISSUE TITLE
表达式分析

### ISSUE THREAD

**Issue by dugenkui03** [killme2008/aviatorscript#365]
## 问题背景
平台继承AbstractFunction实现了自定义函数schedule(‘taskName’)、用于执行指定的逻辑。
执行表达式之前需要判断是否调用了schedule函数，且其任务taskName是否在平台定义。

## 问题描述
请问有办法获取表达式中使用的函数列表、及函数用到的变量嘛。

例如对于表达式 "schedule('aTask') + schedule('bTask') + f2(c)"，分析出：表达式用到了中调用了schedule、用于执行任务aTask 和 bTask。

**Comment by dugenkui03** [comment]
@killme2008 请问现在对这个能力支持嘛［抱拳］

**Comment by killme2008** [comment]
@dugenkui03 不支持，可以通过 Expression#getVariableNames 获取变量名，函数名暂不支持

**Comment by dugenkui03** [comment]
> @dugenkui03 不支持，可以通过 Expression#getVariableNames 获取变量名，函数名暂不支持

请问后续有规划支持嘛、有的话大概多久

**Comment by killme2008** [comment]
@dugenkui03 暂时没计划支持。

**Comment by GoForce5500** [comment]
@killme2008 表达式执行中写入Env的变量列表能增加获取方法么？
比如：
a = 1;
b = a + 1;
return a+b;
上面三句属于同一个表达式，执行后会在Env中增加a,b两个变量，目前无法获取此类变量。
使用场景是定义了多条表达式及相应的执行顺序，其中表达式有可能会通过上述方式写出任意多个值，想校验变量名在每一步执行时是否已经定义。

**Comment by GoForce5500** [comment]
@killme2008 表达式执行中写入Env的变量列表能增加获取方法么？
比如：
a = 1;
b = a + 1;
return a+b;
上面三句属于同一个表达式，执行后会在Env中增加a,b两个变量，目前无法获取此类变量。
使用场景是定义了多条表达式及相应的执行顺序，其中表达式有可能会通过上述方式写出任意多个值，想校验变量名在每一步执行时是否已经定义。
