### ISSUE TITLE
如果存在同名的有参数的getXX方法，这个逻辑是不是取不到无参数的get方法

### ISSUE THREAD

**Issue by llwhub** [killme2008/aviatorscript#368]
https://github.com/killme2008/aviatorscript/blob/c1ffea3a7caac953d0bc931f0f033bfce3ccdcf8/src/main/java/com/googlecode/aviator/utils/Reflector.java#L321

应该改成m.getParameterTypes().length==0吧

**Comment by killme2008** [comment]
发布 5.2.5 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.5
