### ISSUE TITLE
请教一下关于Metaspace回收的技术问题

### ISSUE THREAD

**Issue by shuohao** [killme2008/aviatorscript#372]
![image](https://user-images.githubusercontent.com/4637107/114145977-9a943a80-9949-11eb-94de-6b4ea88cc24b.png)

jdk8，上面这句话里， 如果是采用了cached，默认的concurrentHashMap，这种情况下，AviatorEvaluatorInstance对象是个单例，那是不是永远不会回收？如果动态生成的表达式越来越多metaspace设置的小会OOM。
看了类卸载的条件
![image](https://user-images.githubusercontent.com/4637107/114146945-c237d280-994a-11eb-9d0e-3343efcd7a38.png)
如果要满足这三个条件才能被卸载，如果采用LRU的，匿名类对应堆中的对象没有了，但是加载该匿名类的classloader应该是存活的吧？这样的话匿名类还能卸载吗？

**Comment by killme2008** [comment]
lambda 生成的匿名 class 没有 classloader 的，所以不存在你说的问题。
