### ISSUE TITLE
运行时字符串插值功能的支持

### ISSUE THREAD

**Issue by will86** [killme2008/aviatorscript#375]
您好，作者大神

我在使用aviator5.2.5的库，现有一个字符串插件替换的功能。
在之前5.2.1版本的changelog中看到如下信息：

> • String interpolation only works on literal string in script. Runtime string will not work.

想问下，现在最新的5.2.5运行时能否使用字符串插值功能了，多谢。

**Comment by killme2008** [comment]
这个的意思是不支持一个动态的传入的字符串（通过 env 等方式）做插值，如果的字符串在脚本里是一个 literal （字面量），那是支持的。

比如你有一个字符串是 "#{a}"，这个字符串是通过 env 传入，那不会做插值，如果这个字符串是直接出现在脚本里，会做插值运算。

既然你用 5.2.5 当前跑的版本没有问题，那就不会有问题。
