### ISSUE TITLE
导入实例方法时建议加个重载方法只导入指定的实例方法或指定注解的方法

### ISSUE THREAD

**Issue by Skycat** [killme2008/aviatorscript#377]
RT，在导入实例方法（AviatorEvaluator.addInstanceFunctions）时建议只导入指定的实例方法或指定注解的方法，避免导入很多Object方法和实际无用的方法

**Comment by killme2008** [comment]
可以将不需要导入的标记为 `@Ignore`

`com.googlecode.aviator.annotation.Ignore`

类似这样：

```java
  @Ignore
  public boolean isEmpty(final Number n) {
    return n.longValue() == 0;
  }
```
