### ISSUE TITLE
Hi，请教一下关于大数据量计算的问题

### ISSUE THREAD

**Issue by djx0208** [killme2008/aviatorscript#380]
/**
* 大数据量计算（计算1千万次)
*/
public static void massData() {
FelEngine fel = getEngine();
final Interpreters opti = new Interpreters();
final MutableInt index = new MutableInt(0);
int count = 10 * 1000 * 1000;
final double[] counts = new double[count];
final double[] prices = new double[count];
Arrays.fill(counts, 10d);
Arrays.fill(prices, 2.5d);
opti.add("单价", new Interpreter() {
	@Override
	public Object interpret(FelContext context, FelNode node) {
		return prices[index.intValue()];
	}
});
opti.add("数量", new Interpreter() {
	@Override
	public Object interpret(FelContext context, FelNode node) {
		return counts[index.intValue()];
	}
});
Expression expObj = fel.compile("单价*数量", null, opti);
long start = System.currentTimeMillis();
Object result = null;
for (int i = 0; i < count; i++) {
	result = expObj.eval(null);
	index.increment();
}
long end = System.currentTimeMillis();

System.out.println("大数据量计算:" + result + ";耗时:" + (end - start));
}

对于以上 demo，如果多次调用 massData 方法（多线程），但是不希望多次编译表达式，能否将 expObj 保存起来，每次将 index，counts，prices 通过某种方式传递给 Interpreter？

**Comment by killme2008** [comment]
你的代码是 FEL engine 的，提错地方了吧？ aviator 支持缓存编译模式的

https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#On0Pg
