### ISSUE TITLE
数字多类型 Set include false

### ISSUE THREAD

**Issue by kabayakiuangi** [killme2008/aviatorscript#383]
当一个 set 中包含多种数值类型的值时，因为类型不匹配导致 include 返回 false
例如 
`String script = "include(seq.set(0,3,5,1.2),score)";
        Map<String, Object> params = Maps.newHashMap();
        DoubleStream.of(0, 3, 5, 1.2).forEach(score -> {
            params.put("score",score);
            System.out.println(score + ":" + AviatorEvaluator.execute(script, params));
        });`
脚本中set里的0,3,5被识别为 long ， params 中的 0,3,5为 double，include 类型不匹配返回 false，set 中的数字是否能向上兼容为同一类型呢？

**Comment by killme2008** [comment]
传入的 params 的类型兼容性，需要业务方自己保证，或者在表达式里自己做明确转型，利用 long, double 等函数
