### ISSUE TITLE
How to turn off the console printing?

### ISSUE THREAD

**Issue by shink** [killme2008/aviatorscript#385]
I override the `eval()` function, but a warning is printed to the console when the program starts running. Can the warning not be printed?

![image](https://user-images.githubusercontent.com/49934421/119311562-ceca7d00-bca3-11eb-94fc-8b40e6f701bd.png)

Thank you very much!

**Comment by killme2008** [comment]
Sorry， this warning message can't be turned off, but it prints only once.

**Comment by shink** [comment]
@killme2008 OK, I know. Thank you!
