### ISSUE TITLE
YGC后会重新loader java.lang.invoke.LambdaForm$BMH

### ISSUE THREAD

**Issue by yangxvhao** [killme2008/aviatorscript#386]
public class YxhDemo {

  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  private String uid;

  public String print(String str){
    return str;
  }
}

public class YxhService {

  public String print(String str){
    return str;
  }
}

public class YxhTest {

  private static final AviatorEvaluatorInstance instance = AviatorEvaluator.newInstance();

  public static void main(String[] args) throws Exception {
    instance.importFunctions(YxhService.class);
    YxhService yxhService = new YxhService();
    for (int i = 0; i < 1000000; i++) {
      Map<String, Object> env = new HashMap<>();
      YxhDemo demo = new YxhDemo();
      demo.setUid("123");
      env.put("demo", demo);
      env.put("YxhService", yxhService);
      instance.execute("a = YxhService.print(YxhService,demo.uid)", env, true);
    }

  }
}

JVM参数 -verbose:class -verbose:gc -Xms256M -Xmx256M -Xmn56M
如上代码样例，在运行时如果发生了YGC会重新loader
[Loaded java.lang.invoke.LambdaForm$BMH/901205084 from java.lang.invoke.LambdaForm]
[GC (Allocation Failure)  48620K->5167K(254976K), 0.0060400 secs]
[Loaded java.lang.invoke.LambdaForm$BMH/777457133 from java.lang.invoke.LambdaForm]
[GC (Allocation Failure)  48175K->3887K(254976K), 0.0035014 secs]
[Loaded java.lang.invoke.LambdaForm$BMH/193388045 from java.lang.invoke.LambdaForm]
[GC (Allocation Failure)  46895K->3895K(256000K), 0.0037306 secs]
[Loaded java.lang.invoke.LambdaForm$BMH/136157810 from java.lang.invoke.LambdaForm]
[GC (Allocation Failure)  48951K->3932K(251904K), 0.0042317 secs]
[Loaded java.lang.invoke.LambdaForm$BMH/122155649 from java.lang.invoke.LambdaForm]
[GC (Allocation Failure)  48988K->3989K(254464K), 0.0049246 secs]
[Loaded java.lang.invoke.LambdaForm$BMH/292138977 from java.lang.invoke.LambdaForm]
[GC (Allocation Failure)  46997K->4021K(254976K), 0.0008478 secs]
[Loaded java.lang.invoke.LambdaForm$BMH/748842359 from java.lang.invoke.LambdaForm]
怀疑是com.googlecode.aviator.utils.Reflector#getClassHandles方法缓存的MethodHanler是WeakReference，YGC会清除掉，MethodHandle方法调用checkCustomized优化MethodHandle方法调用checkCustomized优化，调用127次后会生成一个定制LambdaForm，如果频繁发生YGC就会频繁生成LambdaForm

**Comment by killme2008** [comment]
是的，现在部分是用弱引用，会遇到这个问题，预期内。

**Comment by yangxvhao** [comment]
未来会有优化吗，因为这个问题目前我们在使用中遇到了一些性能问题，生产环境每6秒一次YGC，大概有几百个表达式，会加载大量的LambdaForm，我们使用CMS GC，开启了-XX:+CMSClassUnloadingEnabled，CMS GC 最终标记阶段class unloading在6秒以上，如果不开启会导致元空间无限增大。

**Comment by killme2008** [comment]
可以考虑改成 sofa reference

**Comment by killme2008** [comment]
已发布 5.2.6，推荐升级

https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.6
