### ISSUE TITLE
AviatorEvaluator.validate方法似乎不能正确解析if语句

### ISSUE THREAD

**Issue by zarkZz** [killme2008/aviatorscript#387]
各位大佬好，
      我尝试使用AviatorEvaluator.validate("if(1>2){3}")校验这个最基本的表达式，但是会返回异常：
     com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: insert '}' to complete statement at 8, lineNumber: 1, token : [type='Char',lexeme='}',index=8],
while parsing expression: `
if(1>2){3}^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.validate(AviatorEvaluatorInstance.java:1373) ~[aviator-5.1.0.jar:?]
	at com.googlecode.aviator.AviatorEvaluator.validate(AviatorEvaluator.java:488) ~[aviator-5.1.0.jar:?]

      如果我不使用校验，直接AviatorEvaluator.compile(expression, true).execute()就能得到正确的结果。个人目前没有看懂源码逻辑，还请协助检查一下，是否存在问题。

**Comment by killme2008** [comment]
我在最新版本测试没有问题，你的版本多少？

**Comment by zarkZz** [comment]
啊.我的测试版本是5.1.0,现在升级到了5.2.5确实没有问题了。非常感谢~
