### ISSUE TITLE
SeqGetFunction NPE 信息

### ISSUE THREAD

**Issue by dugenkui03** [killme2008/aviatorscript#389]
表达式包含多个`seq.get`的时候如果抛出了npe，通过‘null seq’很难排查到底是哪个导致的，希望在异常信息中加上key、此信息有助于排查问题。

https://github.com/killme2008/aviatorscript/blob/eb6c698603e67d6a9204280412473c19fe13ae5d/src/main/java/com/googlecode/aviator/runtime/function/seq/SeqGetFunction.java#L38

**Comment by killme2008** [comment]
欢迎提个 PR

**Comment by dugenkui03** [comment]
#391 PR已提交
