### ISSUE TITLE
使用中发现nil < 1返回true的情况

### ISSUE THREAD

**Issue by hwxnju** [killme2008/aviatorscript#390]
使用中发现nil < 1, nil < -6等等表达式均不会报错，并且会返回true。
请问这种情况是符合预期的吗？如果这是语法固有特性，那能不能提供一个option用来避免它返回true呢？我的理解是这样的情况应该抛异常的😅

**Comment by killme2008** [comment]
语法规则

https://www.yuque.com/boyan-avfmj/aviatorscript/ugbmqm#uF2Tn
