### ISSUE TITLE
字符串插值时找不到的变量出现了null

### ISSUE THREAD

**Issue by will86** [killme2008/aviatorscript#393]
作者大佬好
我在使用aviator5.2.5的包
现在有一个字符串插值的需要，但传入参数Map对象中，如果有找不到的key，则插值结果出现了”null“这四个字母

` 
       String str = "#{a}";

        StringSegments segments = AviatorEvaluator.getInstance().compileStringSegments(str);

        Map<String, Object> param = new HashMap<>();

        param.put("b", "BBB");

        StringBuilder strBuilder = new StringBuilder();

        for (StringSegment seg : segments.segs) {

            seg.appendTo(strBuilder, param);

        }

        System.err.println(strBuilder.toString());`

如上程序，动态参数中只有b的值，但字符串插值中，需要替换a的值，实际运行结果为null
期望结果为空字符串，而不是四个字母 null

想请教下，如何配置能使插值时，找不到key值的不出现 null 这四个字母呢？
或有其他方法能避开null这四个字母也行，多谢啦！~

**Comment by killme2008** [comment]
null或者 nil，字符串表示就是 `null`，如果你要空白，明确写空字符串 `""`.
