### ISSUE TITLE
在if-else、嵌套if中使用continue无法生效

### ISSUE THREAD

**Issue by saber-Railgun** [killme2008/aviatorscript#394]
使用版本为5.2.1。

for i in range(0, 10) {
	if (i == 3) {
		continue;
	} else {
		let j = 10 + i;
	}
	p(i);
}
如上述代码，参照java中continue的语义，应该不会打印3。但实际运行结果是打印了3，截图如下
![image](https://user-images.githubusercontent.com/24190929/122196360-c263c980-cec9-11eb-877f-bacf28618563.png)

for i in range(0, 10) {
	if (i == 3) {
		continue;
	}
	p(i);
}
如果去掉else，则运行结果就不会打印3了，截图如下
![image](https://user-images.githubusercontent.com/24190929/122196567-ecb58700-cec9-11eb-8779-86e0ebdfc481.png)

根据语雀中对于continue关键字的定义，并没有提到上述相关特性。https://www.yuque.com/boyan-avfmj/aviatorscript/vfqgqn
请问这是个bug还是文档描述不清晰呢？

在嵌套if中同样无法生效。代码示例如下
for i in range(0, 10) {
if (i>3) {
if (i==4){
continue;
}
}
p(i);
}
输出为
![image](https://user-images.githubusercontent.com/24190929/122352772-fef2fc00-cf81-11eb-8638-75f55c8cad00.png)

**Comment by saber-Railgun** [comment]
在嵌套if中同样无法生效。代码示例如下
for i in range(0, 10) {
	if (i>3) {
		if (i==4){
			continue;
		}
	}
	p(i);
}
输出为
![image](https://user-images.githubusercontent.com/24190929/122208862-6fdcda00-ced6-11eb-9888-ca7d0b125d18.png)

**Comment by killme2008** [comment]
似乎是 continue 的 bug，我看下

**Comment by killme2008** [comment]
确认是严重的 bug，惭愧，竟然测试用例没有覆盖到 continue 这个 case，我尽快修复发个版本。

在 continue 出现 else 或者嵌套 if 的场景会出现此不符合预期的行为。

**Comment by saber-Railgun** [comment]
好的，辛苦了。

**Comment by killme2008** [comment]
@saber-Railgun 已修复，可以用 v5.2.6 这个分支来测试，回忆下应该是当时做重构，忘了去掉这个判断条件了，太尴尬了。
https://github.com/killme2008/aviatorscript/pull/376

今天会发布掉 5.2.6

**Comment by killme2008** [comment]
已发布 5.2.6，推荐升级

https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.6
