### ISSUE TITLE
自定义函数计算，精度丢失

### ISSUE THREAD

**Issue by dawnFlyme** [killme2008/aviatorscript#400]
自定义函数cus，执行multiply(85,0.83)时，自定义cus 函数类中AviatorObject接受到的参数已经变为Double类型且0.8300000000000001。目前采用解决办法是cus(85.0,double('0.83')) 可正常获取到0.83。不知还有其他解决办法？

**Comment by killme2008** [comment]
高精度计算请用 decimal 类型
