### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by onlyFcc** [killme2008/aviatorscript#401]
![image](https://user-images.githubusercontent.com/14194756/126734947-89e0923c-1398-44ff-8484-152c13452a04.png)
脚本语句：
![image](https://user-images.githubusercontent.com/14194756/126734995-cd161baa-2c53-4bd7-bc17-19e4699dfbfc.png)
发现有内存泄露问题，dump下来使用mat分析初步定为到这个问题，但不清楚是怎么触发的
![image](https://user-images.githubusercontent.com/14194756/126735113-f3cf7de6-8559-444e-a696-f7ebff8b9eac.png)
![image](https://user-images.githubusercontent.com/14194756/126735194-c28850e7-52eb-4c37-ad2d-3ec5639bf1b4.png)
主要是这个缓存：
![image](https://user-images.githubusercontent.com/14194756/126747888-5e843341-5cde-4fbf-8bde-b85103bc25c5.png)
看了源码，是这个，好像这个没有释放的地方？但是奇怪的是，其他的地方为什么没有发生，之前有用过类似的，但没有出现类似泄漏问题
![image](https://user-images.githubusercontent.com/14194756/126748002-64a6159d-593a-4b91-a4d0-9d8fb7bdc126.png)

**Comment by killme2008** [comment]
版本？

**Comment by onlyFcc** [comment]
> 版本？

用的5.1.0

**Comment by killme2008** [comment]
升级到最新版本吧，老版本有内存泄漏。

**Comment by onlyFcc** [comment]
> 升级到最新版本吧，老版本有内存泄漏。

这边升级了好像是好了，多谢！
能问下泄漏的具体原因吗？因为明明之前也有类似的编译表达式但却没有出现泄露问题。。
这边看泄漏是BaseExpression的stringSegs字段，这是表达式中某一类的编译缓存吗？我看注释是string interpolation.插入类型的字符串吗？不是很理解。。
另外，看两个版本在写入stringSegs上的差异，主要是一个判断，老版本：
![image](https://user-images.githubusercontent.com/14194756/127257811-e7555067-f4a1-43a8-8867-b0a04753f8c6.png)
新版本：
![image](https://user-images.githubusercontent.com/14194756/127257789-87bf3e58-3ce8-48b0-b77b-7860de015d07.png)
新增了!this.isLiteral || !this.hasInterpolation判断，是字面量和上面的插入类型的判断。老版本是较长字符串（lexeme是？）的表达式全部缓存才导致的吗
