### ISSUE TITLE
判断描述逻辑表达式的字符串是否是一个合法的逻辑表达式

### ISSUE THREAD

**Issue by gx9732** [killme2008/aviatorscript#407]
场景是这样的：
用户会根据自己的需求写一些逻辑运算表达式，比如：exp = “name == ‘abcd' && age%2 == 0" (但是此时name，以及age的值并没有传入)， 我们需要验证用户的设定的逻辑表达式exp是否是一个合法的逻辑表达式。
为了验证逻辑描述字符串exp是否是合法的逻辑表达式，我采用的方法是“expression.execute()”， 执行一下，看是否报错，如果报错则不是，如果不报错，则exp描述没问题。但是这种方法并不能很好地解决我的问题。

就刚刚举的例子来看，会报错
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not mod <JavaType, num1, null, null> with <Long, 2>
这是因为age并没有赋值。
所以，我想要请问以下，有没有什么func可以验证逻辑表达式的字符串exp描述是否合法？
（表达式中可能有用户自定义的func，最好是能对func也进行验证）
THX！

**Comment by killme2008** [comment]
这个表达式就是合法的，你要求的 check 变量是不是 nil，这是逻辑的一部分，你可以通过 `Expression#getVaraibleNames` 获取表达式中未初始化的变量名，然后检测传入的 map 是否包含这些变量即可。

函数的检测暂时没有。
