### ISSUE TITLE
bigdecimal运算为0问题

### ISSUE THREAD

**Issue by rboleynl** [killme2008/aviatorscript#409]
开启将整型数字都解析为 BigDecimal，变量计算为0而不是BigDecimal，代码示例
//bigdecimal变量运算
        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL, true);
        AviatorEvaluator.setOption(Options.TRACE_EVAL, true);
        Map<String, Object> expMap = new HashMap<String, Object>();
        expMap.put("loss", 20);
        expMap.put("sum", 100);
        System.out.println("loss变量计算结果:"+ AviatorEvaluator.execute("loss", expMap));
        System.out.println("sum变量计算结果:"+ AviatorEvaluator.execute("sum", expMap));
        System.out.println("20 / 100 计算结果:"+ AviatorEvaluator.execute("20 / 100"));
        System.out.println("(loss/sum)变量计算结果:"+ AviatorEvaluator.execute("loss / sum", expMap));

输出：

loss变量计算结果:20
sum变量计算结果:100
20 / 100 计算结果:0.2
(loss/sum)变量计算结果:0
[Aviator TRACE]          <JavaType, loss, 20, java.lang.Integer> / <JavaType, sum, 100, java.lang.Integer> => <Long, 0>

请问大佬，既然开启了ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL为啥变量计算变为0了而不是BigDecima计算？这种情况该怎么处理，特别是存在嵌套变量的方式，如对象层级a.b.losss，因为设置变量env的时候，具体为一个对象，非单值，如果需要对变量为数字类型再进行强制转换为Bigdecimal的话，还得先解析一遍对象所有层级的类型？有没有方式默认将所有计算都设置为BigDecimal方式？

**Comment by rboleynl** [comment]
可以通过参考代码示例CustomDivideExample自定义重写除法实现，如果为JavaType类型并且为Number类型，直接转化为BigDecima：
if (otherValue instanceof Number) {
         BigDecimal da = new BigDecimal(FunctionUtils.getNumberValue(arg1, env).toString());
         BigDecimal db = new BigDecimal(FunctionUtils.getNumberValue(arg2, env).toString());
}
有没有统一的配置项，统一配置全部BigDecimal计算方式，包括表达式是直接数字以及表达式中的变量为数字的方式；

**Comment by rboleynl** [comment]
参考其他issue，还可以通过类型转化实现：
AviatorEvaluator.execute("decimal(loss) / sum", expMap)

**Comment by killme2008** [comment]
ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL 选项是保证解析的表达式里出现的整数为 decimal，你自己传入的，你要自己保证类型的。
