### ISSUE TITLE
比较符号，上下文为空值 始终返回true

### ISSUE THREAD

**Issue by 18206872076** [killme2008/aviatorscript#410]
e.g
a < 18
a为空 始终返回true

**Comment by rboleynl** [comment]
@18206872076 这个看文档就只到a没有值就是nil，nil小于任何类型，文档有说明

**Comment by 18206872076** [comment]
好的，谢谢解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月3日(周五) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [killme2008/aviatorscript] 比较符号，上下文为空值 始终返回true (#410)




 
@18206872076 这个看文档就只到a没有值就是nil，nil小于任何类型，文档有说明
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
