### ISSUE TITLE
aviator 引入hutool工具类 请问该如何引用

### ISSUE THREAD

**Issue by BleethNie** [killme2008/aviatorscript#414]
使用aviator版本为5.2.7

我是做数据清洗工作的，因为数据清洗方式多种多样，没法在aviator中定义一个，两个，函数解决问题，但是hutool中提供了大量现成的工具类，我想引用hutool中的所有类，该如何实现呢，目前我使用use方法引入date类，但是报错如下：

![image](https://user-images.githubusercontent.com/17614992/133372375-97a193a0-c272-48ad-9223-2f2642fad71d.png)

**Comment by killme2008** [comment]
https://www.yuque.com/boyan-avfmj/aviatorscript/xbdgg2

**Comment by 852675742** [comment]
同求解答如何加载其他非java内置类，使用AviatorEvaluator.addInstanceFunctions加载自定义的工具类也不行啊？
