### ISSUE TITLE
可否关闭部分关键字？

### ISSUE THREAD

**Issue by rboleynl** [killme2008/aviatorscript#417]
可否配置关闭部分关键字功能，只需要基本的表达式功能
        //变量处理：NIL_WHEN_PROPERTY_NOT_FOUND
        AviatorEvaluator.setOption(Options.NIL_WHEN_PROPERTY_NOT_FOUND, true);
        AviatorEvaluator.setOption(Options.FEATURE_SET,
                Feature.asSet(Feature.Assignment, 
                              Feature.ForLoop, 
                              Feature.WhileLoop,
                              Feature.Lambda,
                              Feature.Let
                              //,Feature.If
                              ));
        /*AviatorEvaluator.setOption(Options.FEATURE_SET,
        		Feature.getCompatibleFeatures());*/
        
        System.out.println("根变量含有关键字：if ：" + AviatorEvaluator.execute("if", expMapt1));//报错 :Syntax error: illegal token at 2, lineNumber: 1, token : null while parsing expression: 
        System.out.println("根变量含有关键字：if ：" + AviatorEvaluator.execute("#if", expMapt1));//报错
即使关闭了特性，关键字作为变量还是会解析

**Comment by killme2008** [comment]
那就避免使用这些保留关键字。
