### ISSUE TITLE
ExpressionSyntaxErrorException

### ISSUE THREAD

**Issue by Switcherman** [killme2008/aviatorscript#418]
`com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: unexpect token 'java.util.Date', maybe forget to insert ';'`

用的官方demo,提示引入错误
```java
use java.util.Date;
let d = new Date();

p(type(d));
p(d);
```

**Comment by killme2008** [comment]
确认你的版本吧

**Comment by killme2008** [comment]
use ,let 和 new 语句都只有在 5.x 版本上才能使用，推荐使用 5.2.6 及以上版本。
