### ISSUE TITLE
如果我的规则表达式经常更新， 那是不是很多class信息会占据很多内存, gc会不会无法释放这些内存？

### ISSUE THREAD

**Issue by epiphyllum** [killme2008/aviatorscript#420]
如果我的规则表达式经常更新， 那是不是很多class信息会占据很多内存, gc会不会无法释放这些内存？

**Comment by killme2008** [comment]
不会，参见文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#PMc8K

**Comment by killme2008** [comment]
提醒下，如果使用缓存模式，需要清除缓存，还是阅读上面的文档。
