### ISSUE TITLE
逆波兰表达式（Reverse Polish notation，RPN，亦称为后缀表达式）支持

### ISSUE THREAD

**Issue by jobmission** [killme2008/aviatorscript#422]
感谢作者及贡献者提供这么优秀的作品！

目前项目中不同团队间用到逆波兰表达式相关的功能，能否支持一下?
1、中缀表达式转逆波兰表达式(包含变量)
2、逆波兰表达式计算(包含变量)
...

**Comment by killme2008** [comment]
sorry，不准备支持
