### ISSUE TITLE
  方法找不到 exception:Function not found: DateUtil.betweenMonth

### ISSUE THREAD

**Issue by 9520** [killme2008/aviatorscript#424]
use cn.hutool.core.date.*;

fn monthbet(a,b){
    let format = "yyyy-MM-dd";
    let endDate = string_to_date(b,format);
    let OpenDate = string_to_date(a,format);
    return DateUtil.betweenMonth(OpenDate,endDate,false);
}
println(monthbet('2019-06-00','2021-10-08T11:14:16'));

脚本如上：但是执行时候 提示 exception:Function not found: DateUtil.betweenMonth

**Comment by killme2008** [comment]
依赖包有在 classpath 吗？
