### ISSUE TITLE
建议出一个JS版本

### ISSUE THREAD

**Issue by anyanyna** [killme2008/aviatorscript#427]
建议出一个JS版本

**Comment by killme2008** [comment]
啥意思？ 是说出一个跑在 js 引擎上的 as?

**Comment by anyanyna** [comment]
是的。我现在做一个软件开发平台，前后端都支持用户输入代码片段。所以希望前后端都用同一个语言

**Comment by rboleynl** [comment]
就是前端也有一个表达式引擎，部分工作直接前端处理看到效果，后端也可以解析表达式，前后端一致的引擎

**Comment by anyanyna** [comment]
是的，前端逻辑编排和后端逻辑编排用一样的脚本语言技术，能降低学习门槛


| |
柯贤亮
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月19日 ***@***.***> 写道：

就是前端也有一个表达式引擎，部分工作直接前端处理看到效果，后端也可以解析表达式，前后端一致的引擎

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by metrue** [comment]
Maybe this is want you want. https://github.com/CacheControl/json-rules-engine

**Comment by pruidong** [comment]
可以看看GrallVM,Oracle出的，支持多种语言.
