### ISSUE TITLE
Expression#getVaraibleNames会获取到嵌套作用域中定义的局部变量

### ISSUE THREAD

**Issue by nepheleHu** [killme2008/aviatorscript#431]
Script1 itemV1定义在全局作用域
```
let itemv1 = seq.get(info.value,index);
print( itemv1.name )
```
Expression#getVaraibleNames
`[info, index]`

Script2 itemV1定义在嵌套作用域
```
{
    let itemv1 = seq.get(info.value,index);
    print( itemv1.name )
}
```
Expression#getVaraibleNames
`[info, index, itemv1]`

对于第二种脚本，获取到的未定义变量多了itemv1

**Comment by killme2008** [comment]
这是个 bug，其实是因为引用了 `item1.name` 引起的，会修复下。
