### ISSUE TITLE
com.googlecode.aviator.exception.CompileExpressionErrorException: Blank expression

### ISSUE THREAD

**Issue by jack2020** [killme2008/aviatorscript#433]
![3](https://user-images.githubusercontent.com/3782207/148331022-bdf2102e-25b4-43d5-917c-0846130f409b.png)
![1](https://user-images.githubusercontent.com/3782207/148331029-8ed8ec59-fdab-4bf7-a12d-d76397394479.png)
![2](https://user-images.githubusercontent.com/3782207/148331035-899f3e73-4639-4aca-b219-c6ae1c87f41e.png)
偶尔会报com.googlecode.aviator.exception.CompileExpressionErrorException: Blank expression，但是打印日志expression是存在;

**Comment by killme2008** [comment]
这种问题自己查吧，这种判断如此简单，不会是类库的问题的
