### ISSUE TITLE
自定义函数入参为整形，执行时为long

### ISSUE THREAD

**Issue by lxhdj0215** [killme2008/aviatorscript#436]
public AviatorObject call(
            Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
        List<Object> list = (List<Object>) FunctionUtils.getJavaObject(arg1, env);
        List<Object> subList = (List<Object>) FunctionUtils.getJavaObject(arg2, env);
        boolean bol = list.containsAll(subList);
        return AviatorRuntimeJavaType.valueOf(bol);
    }

表达式：        String expression = "isContains(seq.list(1, 9, 10, 17), visitPurposes)";

![image](https://user-images.githubusercontent.com/30541508/150773175-d65aac02-93fb-4cf2-9690-1d14fa3a52c8.png)

**Comment by killme2008** [comment]
看文档 ， aviator 里的整型只有 long。 https://www.yuque.com/boyan-avfmj/aviatorscript/lvabnw#JQEDA
