### ISSUE TITLE
如何注册全局模块

### ISSUE THREAD

**Issue by chinagoldline** [killme2008/aviatorscript#438]
例如seq创建map的API为：
seq.map();
但是自定义的模块在使用时，却需要每个都要引用模块定义：
let q = require('examples/qsort.av');
目前是否考虑开放自行注册全局模块呀？

**Comment by killme2008** [comment]
首先，还是推荐用 namespace 来隔离，避免命名污染，这也是模块系统的目的。
其次，注册全局可以用 `AviatorEvaluator.addFunction(func)` 等方法，参考 https://www.yuque.com/boyan-avfmj/aviatorscript/xbdgg2
