### ISSUE TITLE
为什么 Map 传参数 Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL 不使其生效

### ISSUE THREAD

**Issue by yudianer** [killme2008/aviatorscript#440]
看文档这个选项在编译脚本文件的时候生效，请问处于什么原因考虑 Map 参数 不能生效呢？

**Comment by killme2008** [comment]
仔细阅读这个选项的说明，always parse floating ..，那就是只在解析阶段生效。 传入的参数请自行保证，作为引擎不会帮你去做默认转换，脚本里的类型会按照 aviator 规范保证。
