### ISSUE TITLE
什么方法可以获取aviator script的执行过程日志

### ISSUE THREAD

**Issue by anyanyna** [killme2008/aviatorscript#441]
前端触发aviator脚本的调试功能后，aviator脚本在后端执行，需要通过后端获取aviator script的执行过程日志，返回给前端展示

**Comment by killme2008** [comment]
启用 `TRACE_EVAL` 选项，并设置你自己的 OutputStream（比如输出到一个 String ），默认是系统输出

```java
AviatorEvaluator.setTraceOutputStream(output)
```

**Comment by anyanyna** [comment]
多谢
