### ISSUE TITLE
希望添加类似于Expression#getVaraibleNames的方法，以获取表达式中所使用到的自定义方法（或者所有方法）

### ISSUE THREAD

**Issue by trytocatch** [killme2008/aviatorscript#445]
希望添加类似于Expression#getVaraibleNames的方法，以获取表达式中所使用到的自定义方法（或者所有方法）。
自己去表达式字符串中查找，不严谨，可能存在转义，或本身是字符串常量而非方法调用的问题

**Comment by argan** [comment]
+1 ， 希望能获取相关的Metadata信息，表达式中使用了哪些函数，或者变量

**Comment by andy-yanggu** [comment]
+1，希望能Expression#getUserDefinedFunction类似的方法，返回自定义函数的元数据，例如返回自定义函数的名称、方法参数等信息。

**Comment by andy-yanggu** [comment]
这个功能有计划做吗

**Comment by deific** [comment]
+1， 希望能获取相关的Metadata信息，表达式中使用了哪些函数，或者变量

**Comment by LoSeitall** [comment]
这个可以先用antlr去实现这个功能，不是很复杂

> +1， 希望能获取相关的Metadata信息，表达式中使用了哪些函数，或者变量

**Comment by killme2008** [comment]
v5.4.2 release https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.2
