### ISSUE TITLE
支持对象取值吗，类似SpringEL那种

### ISSUE THREAD

**Issue by Liubey** [killme2008/aviatorscript#446]
Person person = new Person("Tom", 18); // 一个普通的POJO
parser.parseExpression("#person.name").getValue(context, String.class); 

[aviatorscript](https://github.com/killme2008/aviatorscript)里支不支持类似这种表达式，如persion.age > 18 ? true:false这种？

**Comment by killme2008** [comment]
支持，请阅读文档

**Comment by Liubey** [comment]
@killme2008 抱歉老哥，我就是找了一圈没找到才问的，刚才我又找了一圈。
正在对比和[QLExpress](https://github.com/alibaba/QLExpress)有一些单测可以直接运行，比如https://github.com/alibaba/QLExpress/blob/master/src/test/java/com/ql/util/express/test/ObjectTest.java
抱歉哈

**Comment by killme2008** [comment]
@Liubey 这一节和下一节啊，你说没有我不服啊

https://www.yuque.com/boyan-avfmj/aviatorscript/ugbmqm#kUBD6

**Comment by Liubey** [comment]
@killme2008 无意冒犯。我就是纯粹的没找到，谢谢。我可以和老板说我们可以有俩脚本引擎了😄
