### ISSUE TITLE
编译后的expression 外部缓存支持

### ISSUE THREAD

**Issue by NineBK** [killme2008/aviatorscript#451]
编译后的expression缓存在外部环境中，比如说redis（尝试过，但是无法序列化为Expression）。如果服务多实例部署，缓存在本地是否存在一致性问题

**Comment by hillfly** [comment]
自己做数据一致性保证吧

**Comment by zhang13690** [comment]
我同样有此问题，能详细说下吗 @hillfly

**Comment by killme2008** [comment]
有空我测试下 redis，按理说应该可以

**Comment by lanjiancheng** [comment]
@killme2008 看上去expression没有实现java的序列化接口，不能缓存到外部环境中。

**Comment by killme2008** [comment]
5.4.0 released, ship serialization feature for compiled expression.

See the test case for usage:

https://github.com/killme2008/aviatorscript/blob/master/src/test/java/com/googlecode/aviator/ExpressionSerializeTest.java

The `Option.SERIALIZABLE` must be enabled.

**Comment by killme2008** [comment]
The example

https://github.com/killme2008/aviatorscript/blob/master/src/test/java/com/googlecode/aviator/example/SerializeExample.java
