### ISSUE TITLE
是否有方法可以修改运算符的token或者自己添加新的运算符

### ISSUE THREAD

**Issue by fenghuang316** [killme2008/aviatorscript#453]
您好。不知道有没有方式可以修改运算符的TOKEN或者添加新的运算符，比如我想把&&改为AND

**Comment by killme2008** [comment]
添加运算符搞不了，后续可能支持 macro。

运算符别名可以支持下

**Comment by killme2008** [comment]
5.3.1 支持了逻辑运算符别名，已经发布 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.3.1
