### ISSUE TITLE
表达式短路性能优化：将function重排序放到表达式字符串的最后执行

### ISSUE THREAD

**Issue by tangyang9464** [killme2008/aviatorscript#454]
简单的原生加减比如+,-等执行开销大多情况比函数执行小的多，如果是布尔逻辑运算，那么很多情况可能可以短路运算，不用执行大开销的function。比如function(c,d) && a==b，如果将表达式优化后，function放后面执行也许能减少执行开销。

没有做过太精确的测试，不太清楚在aviator层面上这个优化能否起作用？如果不能原生支持，那应该就只能我们自己优化表达式字符串。
问题来源：[casbin#966](https://github.com/casbin/casbin/pull/966)

**Comment by killme2008** [comment]
aviator 本来就支持短路

**Comment by tangyang9464** [comment]
> aviator 本来就支持短路

@killme2008 我的意思是，用户输入的表达式可能不是最优的，有没有可能由程序来确保优化成最佳的执行。比如用户的表达式是function(c,d) && a==b，程序执行时可以优化成a==b && function(c,d)。当然，这也能由用户来做，不过要确保每个人都知道最佳的表达式写法。

**Comment by killme2008** [comment]
这种只能通过 JIT 来做的，因为 a ==b 是否一直是 false，这个是动态才能决定的，我觉的 JVM 可能也已经做了这个优化了。

**Comment by tangyang9464** [comment]
> 这种只能通过 JIT 来做的，因为 a ==b 是否一直是 false，这个是动态才能决定的，我觉的 JVM 可能也已经做了这个优化了。

不用判断a＝＝b的结果。这个做法就是总是最后执行function，如果a＝＝b为false, 那么就免去执行function，要的是这部分开销的节省。简而言之做法就是能不能将表达式中的function识别出来然后放到后面，就是修改一下表达式的字符串。

**Comment by killme2008** [comment]
这个我建议作为用户指南来提醒吧，这里的假设不一定成立的，方法调用一定慢于逻辑运算符？ 这个不一定的。
