### ISSUE TITLE
建议数组或函数后支持.(点）操作符

### ISSUE THREAD

**Issue by anyanyna** [killme2008/aviatorscript#457]
对含有数组的复杂JSON数据，无法使用.(点）操作符进行后续数据的链式调用。如：
let dataArray = tuple(seq.map('a', 1, 'b', seq.map('b1',11,'b2',12)), seq.map('a', 2, 'b', seq.map('b1',21,'b2',22)));
dataArray[0].a; //报错
(dataArray[0]).a;//报错
seq.get(dataArray,0).a;//报错
(seq.get(dataArray,0)).a;//报错

**Comment by killme2008** [comment]
参见文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ugbmqm#h1jfN

**Comment by anyanyna** [comment]
多谢，改成这种写法是可以的：#dataArray.[0].b.b1
另外，函授调用后面继续使用.(点）操作符（如：(seq.get(dataArray,0)).a），需要怎么做？

**Comment by killme2008** [comment]
这种建议引入一个中间变量，这个本来只是变量的语法糖，并不是语言的一部分。
