### ISSUE TITLE
Boolean表达式计算结果异常 Version 5.3.1 

### ISSUE THREAD

**Issue by sfdan473414** [killme2008/aviatorscript#458]
（1）pom文件引入

            <groupId>com.googlecode.aviator</groupId>
            <artifactId>aviator</artifactId>
            <version>5.3.1</version>

（2）使用scala进行测试
-------------------
    val env = Map("value" -> 2).asInstanceOf[Map[String,Any]]    
 
    val bl = AviatorEvaluator.execute("value > 1 and val < -1 ", AviatorUtil.convertJavaMap(env))    

    println(bl) //  return true    
----------------------

实际结果：表达式 value > 1 and val < -1  的结果返回true
期望结果：产生错误或false，因为没有为 val 设置值。

**Comment by killme2008** [comment]
nil 比任何值都小除了它自己 ，看语法规则 https://www.yuque.com/boyan-avfmj/aviatorscript/ugbmqm#uF2Tn
