### ISSUE TITLE
哪里查看aviatorscript的所有关键字列表么？

### ISSUE THREAD

**Issue by anyanyna** [killme2008/aviatorscript#459]
我现在的功能中，用户可以自定义变量名称，需要校验变量名称不能是aviatorscript的关键字。请问哪里可以查看aviatorscript的所有关键字列表么？

**Comment by killme2008** [comment]
可以调用 `SymbolTable. isReservedKeyword(String)` 方法
https://github.com/killme2008/aviatorscript/blob/master/src/main/java/com/googlecode/aviator/lexer/SymbolTable.java#L68
