### ISSUE TITLE
在脚本里自定义了函数，在编译时会走到onFunctionNotFound

### ISSUE THREAD

**Issue by wl1991** [killme2008/aviatorscript#463]
比如有一段脚本内容，里面有一个函数myfunc：
fn myfunc(l1,l2){
...
}
if myfunc(i,l){
    return 1;
}
return 0;
上述内容保存为一个a.av文件。

代码使用：AviatorEvaluator.getInstance().compileScript(“a.av”, true);进行编译。
在脚本中定义的方法：myfunc，这个方法是用脚本内的实现来执行的，没有自定义函数类，但是在执行编译时会走到FunctionLoader.onFunctionNotFound逻辑，实际会报出：No bean named 'myfunc' available。

请问这个可以避免吗？

**Comment by killme2008** [comment]
`No bean named xxx` 这样的错误并不是 aviator 的，所以我也无从给出任何建议。这段脚本没有什么问题，也能正常编译。
