### ISSUE TITLE
BigDecimal类型精度怎么控制

### ISSUE THREAD

**Issue by xdd715** [killme2008/aviatorscript#464]
1、直接执行表达式里，里面就一个小数，执行结果精度也有改变
   如执行代码 AviatorEvaluator.execute("100.123", null); 得到的结果是100.12299999999999 
    怎么能还返回原来的100.123而不做改变呢。
2、对BigDecimal类型数据取绝对值精度不太对
BigDecimal bigDecimal = new BigDecimal(-1.224);
map.put("num", bigDecimal);
Object execute = AviatorEvaluator.execute("math.abs(num)", map);
执行结果为： 1.2239999999999999769073610877967439591884613037109375
希望得到的结果是 1.224

**Comment by killme2008** [comment]
`Options.MATH_CONTEXT` 选项。

通过 `AviatorEvaluator.getInstance().setOption(Options, Object)` 设置。
