### ISSUE TITLE
重载ADD运算符，运算式报错

### ISSUE THREAD

**Issue by 1633788059** [killme2008/aviatorscript#466]
背景：进行表达式解析的时候，业务场景会出现 A+B的情形， a和b都是具体的业务含义
示例：重写ADD运算符的时候，返回类型为 AviatorRuntimeJavaType.valueOf(Maps.newHashMap())

demo:
    public static void main(final String[] args) {
        
        AviatorEvaluator.getInstance().addOpFunction(OperatorType.ADD, new AbstractFunction() {

            @Override
            public AviatorObject call(final Map<String, Object> env, final AviatorObject arg1,
                final AviatorObject arg2) {
                Map<String, Object> test = Maps.newHashMap();
                test.put("test", "123");
                return AviatorRuntimeJavaType.valueOf(test);
            }

            @Override
            public String getName() {
                return OperatorType.ADD.getToken();
            }
        });

        Expression compiledExp3 = AviatorEvaluator.compile("10000+ 20000 ");
        System.out.println(compiledExp3.execute());
    }
    
    10000 和 20000 有实际的业务含义，所以才想着返回map类型出来

问题：执行过程报错
Exception in thread "main" com.googlecode.aviator.exception.CompileExpressionErrorException: Invalid operand:<JavaType, A_1, {}, java.util.HashMap>

想请教一下，怎么避免这个问题，使得能返回自定义的类型。
（是否有一些配置项之类的，谢谢了）

**Comment by 1633788059** [comment]
改成 ‘10000’ + ‘20000’ 是可以出来想要的效果，
看了一下代码，是在compile的时候，判断是否要提前执行的逻辑，应该是做优化使用的。
代码在OptimizeCodeGenerator#executeOperator
 // if we can execute it on compile
    if (canExecute) {
      // arguments
      AviatorObject[] args = new AviatorObject[operandCount];
      int index = 0;
      for (int j = operandStartIndex; j < operatorIndex; j++) {
        token = this.tokenList.get(j);
        if (token.getType() == TokenType.Delegate) {
          this.tokenList.set(j, null);
          continue;
        }
        args[index++] = getAviatorObjectFromToken(token);
        // set argument token to null
        this.tokenList.set(j, null);

      }
      AviatorObject result = OperationRuntime.eval(getCompileEnv(), args, operatorType);
      // set result as token to tokenList for next executing
      this.tokenList.set(operatorIndex, getTokenFromOperand(operatorToken, result));
      return 1;
    }

问题：能否叫一个配置项之类的，来决定是否在compile就计算结果，谢谢了

**Comment by killme2008** [comment]
关闭优化：

```java
AviatorEvaluator.getInstance().setOption(Options.OPTIMIZE_LEVEL, AviatorEvaluator.COMPILE);
```

**Comment by 1633788059** [comment]
@killme2008 关闭优化 有什么其他的性能影响吗，想问一下这个有文档吗？

**Comment by killme2008** [comment]
目前也只做了常量折叠的优化，理论上对运行时性能有少许影响

所有选项都在文档库有说明 https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau

**Comment by 1633788059** [comment]
正式版本是多少，我升级一下

**Comment by 1633788059** [comment]
@killme2008  你好，麻烦问下这个一般多久升一次版本哈，还是想升级到最新版本，解决这个问题，谢谢了
