### ISSUE TITLE
有没有基于 aviatorscript规则引擎开源框架

### ISSUE THREAD

**Issue by kiwimg** [killme2008/aviatorscript#467]
有没有基于 aviatorscript规则引擎开源框架，能推荐一下吗

**Comment by wadekun** [comment]
我们一开始也是想直接用开源封装好的规则引擎，看了好多开源实现，没有发现很好用的。最后是基于aviatorscript开发了一套。
规则引擎的核心功能就是根据业务规则快速生成响应的脚本语句（业务规则到脚本语句的转换），然后执行脚本语句反回响应结果（脚本执行引擎）。其中脚本执行引擎也就是aviatorscript，这个与业务没有直接关系，可以很好的封装实现。业务规则到脚本语句的转换 这个和业务有比较强的关系，很难做成很通用的，drools也是提供了一套接口需要传入业务对象来编写规则，维护起来也是比较麻烦笨重。
最好的方式还是根据自己的业务逻辑，封装一些自己的函数库，定义好规则抽象，维护好业务规则到脚本语句的转换逻辑。来实现一套符合自己业务的规则引擎。

**Comment by kiwimg** [comment]
谢谢您详细的回答 感谢，基本这个思路，如果有类似框架就好了
