### ISSUE TITLE
find boolean Expressin bug

### ISSUE THREAD

**Issue by xkernal** [killme2008/aviatorscript#468]
expression: (act_u_082>=10||(act_u_177>=101&&act_u_177<=200)||act_u_201<=3)&&attr_u_001==1
Expression compiledExp = AviatorEvaluator.compile(expression);
Map<String, Object> env = new HashMap<>();
env.put("attr_u_001", 1);
Boolean result = (Boolean) compiledExp.execute(env);

expect return:false,but return true

**Comment by killme2008** [comment]
Set the option `Options.TRACE_EVAL` to be `true`, then you will know why it happened.

`java
  AviatorEvaluator.setOption(Options.TRACE_EVAL, true);
```

Note: `nil` is less than any values except itself.
