### ISSUE TITLE
Expression.getVariableFullNames()返回结果bug

### ISSUE THREAD

**Issue by zondacker** [killme2008/aviatorscript#476]
如题，Expression.getVariableFullNames()在以下场景会返回不太正确的结果：
示例脚本：
Expression expr = instance.compile("let abc = new String('abc');", true);
System.out.println(expr.getVariableFullNames());

返回结果：
[String]

**Comment by killme2008** [comment]
Fixed in 5.3.2 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.3.2
