### ISSUE TITLE
Why not modify the input parameters？

### ISSUE THREAD

**Issue by Sirius-LeeFeng** [killme2008/aviatorscript#480]
version -> com.googlecode.aviator:aviator:5.3.1

expression:
(1.0M+a)/2.1

Made
ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL = true ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL = true

Shall we modify the dot "a" = BigDecimal.valueOf(a).setScale(precision) before "execute0()" ?

**Comment by killme2008** [comment]
Sorry , i don't understandard what you mean.

**Comment by Sirius-LeeFeng** [comment]
The `ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL= true`  obviously makes people think that `the floating-point values  in the expression `and `input parameters`  will be converted into decimal. Is it possible to selectively implement this feature?
 
 Shall we modify `input parameters  【a】` into `decimal`?

**Comment by killme2008** [comment]
`ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL` is only effect on floating point number **literal**,it's user's responsibility to ensure input  variables type are correct.

**Comment by Sirius-LeeFeng** [comment]
I do, new friends may need it. Even better as an optional feature. hhhh...
`ALWAYS_CAST_FLOATING_POINT_NUMBER_INTO_DECIMAL`
