### ISSUE TITLE
jdk17兼容性问题，ClassDefiner中static代码块无法正常执行

### ISSUE THREAD

**Issue by inpore** [killme2008/aviatorscript#482]
jdk17已经移除了sun.misc.Unsafe.defineAnonymousClass方法，ClassDefiner static初始化的时候会报nosuchmethod异常，大佬看看是否可以兼容下

**Comment by killme2008** [comment]
异常理论上不影响，会退化成 classloader 方式去定义

**Comment by inpore** [comment]
这个通过sun.misc.Unsafe.defineAnonymousClass和通过classloader定义会有区别吗
我这边是使用自定义类加载器加载jar包，之前自定义类加载器只实现了findclass方法打破双亲委派，jdk8的时候都正常，升级到jdk17后由于defineAnonymousClass失效了变成通过loadclass方法加载，由于我们容器内也有这个依赖，导致定义过程出了一些classcast的异常

**Comment by killme2008** [comment]
你可以传入你自定义的 classloader ，通过 `AviatorEvaluator.setAviatorClassLoader(new AviatorClassLoader(yourClassLoader))`.

会有一些区别，具体见文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#PMc8K

**Comment by inpore** [comment]
thanks
