### ISSUE TITLE
使用双斜线注释代码编译不报错，但代码运行结果不对

### ISSUE THREAD

**Issue by zhengshg** [killme2008/aviatorscript#483]
问题：代码中注释误使用成双斜线//,但编译并没有报错，但代码不符合预期，版本：5.3.0
---------------------------
代码：
if( !string.startsWith(tableName, "test")){
    return false;
}
//注释xxxx
return true;

测试数据：
{"tableName":"notest"}
-----------------------------
预期：返回false，实际：返回true

**Comment by killme2008** [comment]
这是个 bug，感谢报告

**Comment by killme2008** [comment]
Fixed in 5.3.2 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.3.2
