### ISSUE TITLE
如果这个表达式是由用户输入的   如何防止用户恶意输入呢

### ISSUE THREAD

**Issue by xql66666** [killme2008/aviatorscript#485]
例如用户输入下面类似的片段
System.out.println(AviatorEvaluator.execute("Thread.sleep(3000)"));
System.out.println(AviatorEvaluator.execute(" System.exit(0)"));

**Comment by killme2008** [comment]
设置白名单，参考最佳实践文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#elOSu
