### ISSUE TITLE
关于逻辑运算输出结果的疑惑

### ISSUE THREAD

**Issue by CoderDinosaur** [killme2008/aviatorscript#486]
环境： Ubuntu 18.06.6 LTS, JDK 1.8.0_30,  Aviator  5.3.1

最近使用 Aviator引擎 进行逻辑运算， 发现使用不同的数学符号，在放入的变量名与逻辑表达式的变量名不同时，会出现不同的执行结果

`//example

        Expression exp1 = AviatorEvaluator.compile("a == 0M");
        System.out.println(exp1.execute(exp1.newEnv("k", 10)));  //false

        Expression exp2 = AviatorEvaluator.compile("b > 1M");
        System.out.println(exp2.execute(exp1.newEnv("k", 10)));  //false

        Expression exp3 = AviatorEvaluator.compile("c >= 2M");
        System.out.println(exp3.execute(exp1.newEnv("k", 10)));  //false

        Expression exp4 = AviatorEvaluator.compile("d != 3M");
        System.out.println(exp4.execute(exp1.newEnv("k", 10)));  //true

        Expression exp5 = AviatorEvaluator.compile("e < 4M");
        System.out.println(exp5.execute(exp1.newEnv("k", 10)));  //true

        Expression exp6 = AviatorEvaluator.compile("f <= 5M");
        System.out.println(exp6.execute(exp1.newEnv("k", 10)));  //true`

总结执行结果，当map中放入的变量名与逻辑表达式的变量名不同，且
                               符号为(==,>,>=)时： 表达式结果为 false
                               符号为(!=,<,<=)时：  表达式结果为 true

预期结果：因为map中放入的变量名与逻辑表达式的变量名都不同， 所以结果应该全为false

也许上述情况是您设计上的特点，只不过十分期待您为我解答这个疑惑

**Comment by killme2008** [comment]
这里不是什么变量不同，没有传入就是 nil，nil 比任何其他值都要小，除了它本身。

文档都有写到，注意阅读。

**Comment by CoderDinosaur** [comment]
是我粗心了......&nbsp; &nbsp;非常感谢您的解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "killme2008/aviatorscript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [killme2008/aviatorscript] 关于逻辑运算输出结果的疑惑 (Issue #486)





 
这里不是什么变量不同，没有传入就是 nil，nil 比任何其他值都要小，除了它本身。
 
文档都有写到，注意阅读。
