### ISSUE TITLE
数学函数double 处理异常

### ISSUE THREAD

**Issue by zlongyue** [killme2008/aviatorscript#488]
aviator.version: 5.3.1
ExpressionLexer 在解析double 类型时，会导致数据异常。
math.abs(-51.34) 执行后的结果为51.339999999999996 ，但是java的math abs函数处理的结果为51.34
通过跟踪发现com.googlecode.aviator.lexer.ExpressionLexer 类在处理到小数时的代码如下（257-258行）
`           dval = dval + digit / d;
            d = d * 10;
`
dval = dval + digit / d 会导致出现错误，建议这里使用BigDecimal进行处理，以防止出现和java 默认函数出现不一样的结果。

**Comment by killme2008** [comment]
要追求精度，就直接用 decimal 类型，写成 `-51.34M` 即可， aviator 是本身就支持。 浮点数的精度问题不再赘述了。
