### ISSUE TITLE
如果在多个表达式中定义同名局部变量，在多线程环境下表达式的计算偶尔会出现错误

### ISSUE THREAD

**Issue by adny-yanggu** [killme2008/aviatorscript#489]
import com.googlecode.aviator.AviatorEvaluator;
import com.googlecode.aviator.AviatorEvaluatorInstance;
import org.junit.Test;

import java.util.HashMap;
import java.util.concurrent.CountDownLatch;

public class Test2 {

    @Test
    public void test1() throws Exception {

        int value = 2;
        CountDownLatch countDownLatch = new CountDownLatch(value);
        HashMap<String, Object> env = new HashMap<>();
        env.put("b", value);

        for (int i = 0; i < 2; i++) {
            int finalI = i;
            new Thread(() -> {
                AviatorEvaluatorInstance instance = AviatorEvaluator.newInstance();
                Object result = instance.compile("a = b + " + finalI + ";\n" +
                    "a + 1", true).execute(env);
                System.out.println(finalI + " -> result: " + result);
                countDownLatch.countDown();
            }).start();
        }
        countDownLatch.await();
        //实际输出
        //0 -> result: 3
        //1 -> result: 3
        //预期输出
        //0 -> result: 3
        //1 -> result: 4
    }

}

**Comment by killme2008** [comment]
Map 不是线程安全的，这个问题完全是你用法的问题，再想想吧。

**Comment by adny-yanggu** [comment]
@killme2008 使用了线程安全的ConcurrentHashMap仍然偶尔会出现错误，已经试过了，大概是50%的概率会出现

**Comment by killme2008** [comment]
加上这行
```
instance.setOption(Options.USE_USER_ENV_AS_TOP_ENV_DIRECTLY, false);
```

为啥呢？ 看 https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#USE_USER_ENV_AS_TOP_ENV_DIRECTLY

**Comment by adny-yanggu** [comment]
@killme2008 可以了，谢谢
