### ISSUE TITLE
关系运算符中NULL咨询

### ISSUE THREAD

**Issue by wr345861927** [killme2008/aviatorscript#493]
你好,我们在项目中遇到了一个问题.发现在数字和NULL做关系比较时,NULL是作为无限小,但是在实际场景中经常遇到NULL是一个有效值,既不大于也不小于,因此更期望提示一个错误,所以是否可以提供一个开关切换当前这种状态呢

**Comment by killme2008** [comment]
你可以重载所有的比较运算符来实现，如果任何一个参数是 null，就报错
