### ISSUE TITLE
ThreadLocal cache for lambda may consume too much memory

### ISSUE THREAD

**Issue by killme2008** [killme2008/aviatorscript#494]
Consider to use weak or soft reference.

**Comment by killme2008** [comment]
5.3.3 released https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.3.3

**Comment by redolog** [comment]
请教作者这里的改动点。

使用了softReference，如果应用内存紧张，而aviator脚本还没执行完成，我理解是有可能 LambdaFunction已经被回收掉了，这时候结果不就出错了吗？
