### ISSUE TITLE
json循环依赖问题

### ISSUE THREAD

**Issue by TheMrCoder** [killme2008/aviatorscript#497]
你好，我在修改Map时，出现了$的引用符号，这个如何处理。
脚本：seq.put(context,"info",context.label);
结果：{"label":"abc","info":{"$ref":"$.label"}}

预期的结果是：{"label":"abc","info":"abc"}

**Comment by killme2008** [comment]
这跟 aviator 没什么关系，跟你用的 json 库有关系，我猜测是 fastjson， 去那边问吧。
