### ISSUE TITLE
是否有可能让Expression实现序列化接口，以便于使用第三方中间件进行组织和缓存

### ISSUE THREAD

**Issue by WJHarry** [killme2008/aviatorscript#499]
目前看到Expression是没有实现序列化接口的，因此无法使用JDK的序列化/反序列化方法对编译结果进行序列化，而在集群中，将编译结果托管给第三方的缓存中间件是一个比较常见的需求。或者作者是否有更好的办法实现这样的效果呢？

**Comment by Topcoder2023** [comment]
同样的问题，希望有高手帮忙解答一下

**Comment by killme2008** [comment]
v5.4.1 已经支持

https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.1

例子

https://github.com/killme2008/aviatorscript/blob/master/src/test/java/com/googlecode/aviator/example/SerializeExample.java
