### ISSUE TITLE
完善validate,compile的校验功能

### ISSUE THREAD

**Issue by batmanhaha** [killme2008/aviatorscript#501]
目前问题:

1. a5 无法校验出dsl中不支持的方法, （<5 版本complie是可以的）
2. 设置FEATURE_SET 也是无法在compile 和validate中 校验出不支持的feature

目前妥协的方法是 空跑下再根据异常类型做判断

**Comment by killme2008** [comment]
validate 仅校验语法，目前不会去做运行时校验。部分 feature 是要运行时才能校验。
