### ISSUE TITLE
5.0之后版本和5.0之前版本的include函数为啥有区别？且5.1.3版本的include函数对set集合支持会有问题

### ISSUE THREAD

**Issue by fengdis** [killme2008/aviatorscript#511]
![image](https://user-images.githubusercontent.com/26568314/210945688-e5237db0-0b71-4b5b-a37c-d955abd9775a.png)
![image](https://user-images.githubusercontent.com/26568314/210945737-d8159619-dc3c-4fce-9eea-018d22f09099.png)
第二张图中set集合中如果为Integer类型的，会返回false

**Comment by killme2008** [comment]
这是针对 `Set` 的性能优化，直接走 `Set#contains` 方法，理论上可以做到 O(1) 的时间复杂度，原来实现是 O(n)。

但是确实会引入你提到的这个问题，目前是需要用户保证通过 env 传入的类型，都转换成 aviatorscript 支持的类型，比如所有整形都转换为 long。

**Comment by fengdis** [comment]
后续有望支持全类型吗😊
