### ISSUE TITLE
5.3.3版本还是会发生内存泄露

### ISSUE THREAD

**Issue by jack-hurricane-hu** [killme2008/aviatorscript#514]
![image](https://user-images.githubusercontent.com/48268637/217241916-7edea7d0-fdb7-42bf-bbdb-141503965e20.png)

**Comment by killme2008** [comment]
从你的截图来看并不能证明内存泄露的，内存泄露有很多排查工具，可以自行再分析下。

**Comment by jack-hurricane-hu** [comment]
> 从你的截图来看并不能证明内存泄露的，内存泄露有很多排查工具，可以自行再分析下。

我间隔了一段时间，再次去看Env占用的内存，好像一直在上升，但是比较缓慢
![image](https://user-images.githubusercontent.com/48268637/217428607-9dfe84a1-bcab-47a2-882b-62b2f8ce5d5f.png)

**Comment by killme2008** [comment]
内部的 cache 是软引用，只有在空间不足的时候才会回收，充分利用内存做 cache。 所以你看到这种瞬间状态没有太大意义，除非确实 OOM，或者 jprofile 、MAT 等工具提示你内存泄露，否则没法评价。
