### ISSUE TITLE
并发使用aviator计算，在到达一定并发量时出现blocked【请教】

### ISSUE THREAD

**Issue by jiudc** [killme2008/aviatorscript#521]
这种是属于并发加载类时导致的blocked，我如何查看是由于加载哪个类导致的，想通过提前加载的方式解决；
是否有其他解决该问题的途径。
"QueryPool-592" #1051 prio=5 os_prio=0 tid=0x0000000001525800 nid=0x9f2 waiting for monitor entry [0x00007fd3200c3000]
12116    java.lang.Thread.State: BLOCKED (on object monitor)
12117     at java.lang.ClassLoader.loadClass(ClassLoader.java:404)
12118     - waiting to lock <0x0000000645822fb8> (a java.lang.Object)
12119     at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
12120     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12121     at java.lang.Class.forName0(Native Method)
12122     at java.lang.Class.forName(Class.java:264)
12123     at com.googlecode.aviator.utils.Env.classForName(Env.java:278)
12124     at com.googlecode.aviator.utils.Env.resolveClassSymbol(Env.java:181)
12125     at com.googlecode.aviator.utils.Env.resolveClassSymbol(Env.java:168)
12126     at com.googlecode.aviator.runtime.type.AviatorJavaType.tryResolveAsClass(AviatorJavaType.java:457)
12127     at com.googlecode.aviator.utils.Reflector.fastGetProperty(Reflector.java:813)
12128     at com.googlecode.aviator.runtime.type.AviatorJavaType.getProperty(AviatorJavaType.java:438)
12129     at com.googlecode.aviator.runtime.type.AviatorJavaType.getValueFromEnv(AviatorJavaType.java:337)
12130     at com.googlecode.aviator.runtime.type.AviatorJavaType.getValue(AviatorJavaType.java:320)
12131     at com.googlecode.aviator.runtime.type.AviatorNil.innerCompare(AviatorNil.java:62)
12132     at com.googlecode.aviator.runtime.type.AviatorObject.compare(AviatorObject.java:80)
12133     at com.googlecode.aviator.runtime.type.AviatorObject.compareEq(AviatorObject.java:71)
12134     at Script_1677587023159_85/1620684738.execute0(Script_1677587023159_85:5)
12135     at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:44)
12136     at com.googlecode.aviator.runtime.function.LambdaFunction.call(LambdaFunction.java:115)
12137     at Script_1677587023152_68/178281116.execute0(Script_1677587023152_68:3)
12138     at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:44)
12139     at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:246)

**Comment by killme2008** [comment]
BLOCKED 不要紧，他只是线程的一个瞬间状态。

是影响了吞吐还是 latency ?

**Comment by jiudc** [comment]
都影响了。我这边尝试修改了下，将加载类为null的情况也加入了缓存管理，在一定程度上减少了block的概率。我后续想通过预热的方式将表达式和需要加载的类提前加载，麻烦看看有没有其他思路以及这块是否可以如此优化？
![image](https://user-images.githubusercontent.com/3376011/222845104-56d64728-52df-4227-ab9e-4db63039084d.png)

**Comment by killme2008** [comment]
欢迎将你的改进贡献过来，提个 PR。
预热是个办法，但是需要提前知道你的所有使用到反射的类，基本就是使用了 `a.b.c` 类似语法的类。
