### ISSUE TITLE
boolean 类型转换的语义定义成和Java的Boolean.valueOf一致更好？

### ISSUE THREAD

**Issue by losor** [killme2008/aviatorscript#531]
boolean 函数现在定义为 nil 或 false (AviatorBoolean.FALSE) 为false，其它为true。
5.3.3中代码如下

    @Override
    public AviatorObject call(final Map<String, Object> env, final AviatorObject arg1) {
        switch (arg1.getAviatorType()) {
            case Boolean:
                return arg1;
            default:
                if (arg1.getValue(env) == null) {
                    return AviatorBoolean.FALSE;
                } else {
                    return AviatorBoolean.TRUE;
                }
        }
    }

考虑下面的使用方式：

        Expression exprWithoutVariable = AviatorEvaluator.compile("boolean(false)");
        Expression exprWithFalseVariable = AviatorEvaluator.compile("boolean(var)");

        Map<String, Object> variables = new HashMap<>();

        System.out.println(exprWithoutVariable.execute(variables));

        variables.put("var", AviatorBoolean.FALSE);
        System.out.println(exprWithFalseVariable.execute(variables));

        variables.put("var", false);
        System.out.println(exprWithFalseVariable.execute(variables));

        variables.put("var", "false");
        System.out.println(exprWithFalseVariable.execute(variables));

我们是不是更倾向于这些情况都是false？而不是后3种都是true

> false
> true
> true
> true

我觉得可以这样改：

    @Override
    public AviatorObject call(final Map<String, Object> env, final AviatorObject arg1) {
        switch (arg1.getAviatorType()) {
            case Boolean:
                return arg1;
            default:
                Object var = arg1.getValue(env);
                if (var == null) {
                    return AviatorBoolean.FALSE;
                } else {
                    return AviatorBoolean.valueOf(Boolean.parseBoolean(var.toString()));
                }
        }
    }

下面是我的思考:

1. 对于AviatorBoolean，实际上不需要加 boolean()来转换
2. 对于变量 nil 作为Boolean，更适合的写法我觉得是 var == nil 或 var != nil，而不是 boolean(var)
3. boolean(var) 当var为 "false"时，返回true不合常理

**Comment by killme2008** [comment]
你可以提供自己的 `bool` 函数，标准实现考虑到兼容问题，不会改动。
