### ISSUE TITLE
请问Expression.execute(Map<String,Object>)是否是线程安全的？

### ISSUE THREAD

**Issue by gzz100** [killme2008/aviatorscript#533]
我想先AviatorEvaluator.compile好一个Expression对象，然后多线程并发调用这个Expression对象去execute（Map数据是线程安全的），是否线程安全？

**Comment by killme2008** [comment]
安不安全取决于你表达式干什么，你的表达式如果修改共享变量，那就可能出问题。所以这个问题跟 aviatorscript 是无关的，是你自己决定的。
