### ISSUE TITLE
class<T> 这种java函数，如果aviator脚本中调用，请问参数如何传值？

### ISSUE THREAD

**Issue by peterxiemin** [killme2008/aviatorscript#534]
public static <T> T json2Object(String json, Class<T> c) {
        if (StringUtils.isNotBlank(json) == false)
            return null;

        T t = null;
        try {
            t = (T) mapper.readValue(json, c);
        } catch (Exception e) {
            log.info("[JsonUtil object2Json] fail, json:{}", json, e);
        }
        return (T) t;
    }

**Comment by killme2008** [comment]
不需要传,java 的泛型实现是擦拭法，运行时没有的

**Comment by peterxiemin** [comment]
抱歉，我想问的是不是T应该怎么传，而是Class类型怎么传，在文档中确实没找到。
