### ISSUE TITLE
访问map时，如果key为整数类型时，会取不到数据

### ISSUE THREAD

**Issue by walterlife** [killme2008/aviatorscript#538]
目前取map中key的数据类型为不支持为整数的场景，只支持map-key的数据类型为字符串。
具体代码：com.googlecode.aviator.utils.Reflector
![image](https://user-images.githubusercontent.com/8448852/236787984-e432cbf4-5649-4963-82b7-79aee776eb15.png)
比如let x = #m.21007，如果原始数据map中 21007 是整数类型，则会出现取不到值的case

**Comment by killme2008** [comment]
可以用 `m[21007]` ， map 也支持索引语法，再不行还可以 `seq.get(m, 21007)`.
