### ISSUE TITLE
关于脚本校验问题

### ISSUE THREAD

**Issue by SUSTCFather** [killme2008/aviatorscript#541]
作者你好，我这边遇到一个困难，就是在跳过运行阶段，去校验脚本的正确性，比如需要获取所有的变量、和获取所有的调用的函数。
获取所有变量好像可以通过getVariableFullNames()获取，但是获取脚本内调用的函数，无法获取，想看看有没啥好办法

**Comment by qichhhhh** [comment]
将 __env__ 返回后通过 com.googlecode.aviator.utils.Env 里的相关方法可以获取到脚本内的函数列表

**Comment by killme2008** [comment]
v5.4.2 release https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.2
