### ISSUE TITLE
有比较好用的aviatorscript编辑器推荐吗？

### ISSUE THREAD

**Issue by peterxiemin** [killme2008/aviatorscript#544]
有比较好用的aviatorscript编辑器推荐吗？

**Comment by mjg2091864671** [comment]
同求

**Comment by killme2008** [comment]
可以试试这个 idea 插件 https://github.com/yanchangyou/aviatorscript-ideaplugin

**Comment by mjg2091864671** [comment]
@killme2008 这个好像不支持新版的idea😂

**Comment by killme2008** [comment]
我看作者已经修复了，你可以在该项目提需求的。
