### ISSUE TITLE
请教大家，有api能够获取当前计算表达式的返回值类型吗？

### ISSUE THREAD

**Issue by 1024lzx** [killme2008/aviatorscript#545]
大佬们好，我现在有一个需求
特定场景下，用户填写的表达式必须满足返回值是一个bool类型的结果，但是debug了一下代码，没有发现明显的api能够满足需求，求教各位大神，能够给点思路，感谢【小花】

**Comment by andy-yanggu** [comment]
我遇到过类似的需求，我的做法是给表达式依赖的变量注入随机值，然后执行表达式，看表达式的返回值是不是boolen，如果不是就报错。表达式依赖的变量，必须知道具体的数据类型。例如Int类型具体的值。如果不知道变量的数据类型没法处理

**Comment by 1024lzx** [comment]
感谢您百忙之中回复我的问题【送花花】
我找到了一个替代的解决，依托与apache jexl工具能够解析出表达式的ast抽象语法树，然后解析抽象语法树的根节点，判断类型是否是我们关心的类型
https://commons.apache.org/proper/commons-jexl/
您说的这个方案也很好，我会仔细考虑如何实现，再次表示感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "killme2008/aviatorscript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [killme2008/aviatorscript] 请教大家，有api能够获取当前计算表达式的返回值类型吗？ (Issue #545)





 
我遇到过类似的需求，我的做法是给表达式依赖的变量注入随机值，然后执行表达式，看表达式的返回值是不是boolen，如果不是就报错。表达式依赖的变量，必须知道具体的数据类型。例如Int类型具体的值。如果不知道变量的数据类型没法处理

**Comment by 1024lzx** [comment]
已解决
