### ISSUE TITLE
打开trace_eval后执行以下代码报错

### ISSUE THREAD

**Issue by 1sua** [killme2008/aviatorscript#547]
打开trace_eval后执行以下代码报错
`let a = nil;`
`let flag = a != nil && double(a) != 0;`

**Comment by 1sua** [comment]
@killme2008

**Comment by killme2008** [comment]
咱们报告一个 bug，是不是应该写的完整一些？ 比如把报错信息附上。

**Comment by killme2008** [comment]
这是因为启用了 `TRACE_EVAL` 后，短路规则失效引起的，文档里有注明。
短路失效后， `double(nil)` 将抛出异常。
