### ISSUE TITLE
如何在 JAVA 环境获取到脚本运行完时各个变量的值？

### ISSUE THREAD

**Issue by qichhhhh** [killme2008/aviatorscript#548]
#108  问题和这个类似，我们目前是传入了一些自定义的中间变量，脚本内容类似：
`
let c座位险 = 机动车损失保险保费 + 机动车第三者责任保险保费;
let c座位险每座保额 = c座位险 / 车座数;
return  c座位险每座保额 > 100;
`
然后通过 拼凑一个 Map<String, Object> env 传入 expression.execute(env); 
我现在只能获取表达式的 boolean 型返回结果，我想把 c座位险 和 c座位险每座保额 的值也获取到，用于返回给运营人员查看，这样该如何做呢？
在 #108  中看到的 print(__env__) 只能将上下文环境打印出来

**Comment by qichhhhh** [comment]
@killme2008

**Comment by NiMengSL** [comment]
搞个对象或者map?

**Comment by killme2008** [comment]
你要么连同表达式结果一起返回，否则没有别的办法。

`return seq.list(c座位险每座保额 > 100, c座位险每座保额)`

然后在应用层处理。
