### ISSUE TITLE
请教一个getVariableFullNames的问题

### ISSUE THREAD

**Issue by cyningchen** [killme2008/aviatorscript#549]
`let appkey = get_appkey("com.sankuai.aaa.bbb.ccc");
if appkey != nil{
   return appkey.serviceLevel;
}
return nil;`

getVariableFullNames返回["appkey.serviceLevel"]，与预期为[]不一致，请问是feature还是bug

**Comment by killme2008** [comment]
是个 bug，已在 https://github.com/killme2008/aviatorscript/commit/3716a6c429c62117f811b8087d52d885562c0eef 修复

**Comment by killme2008** [comment]
Released 5.4.3
