### ISSUE TITLE
【BUG】条件语句返回异常

### ISSUE THREAD

**Issue by oooqqqooo** [killme2008/aviatorscript#554]
let result = nil;
if a == 1 {
    result = 2;
} elsif a == 0 {
    return 1;
}
return result;

上述代码当a=1时返回为null，请问这是什么问题

**Comment by killme2008** [comment]
看起来是 elsif 和 return 在一起有个bug，我这周确认并修复下。

**Comment by killme2008** [comment]
Fixed in v5.4.0 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.0
