### ISSUE TITLE
请问下什么场景下会出现这个报错呢 Could not bitAnd <Boolean, false> with <Boolean, false> ？

### ISSUE THREAD

**Issue by 18206872076** [killme2008/aviatorscript#558]
com.googlecode.aviator.runtime.type.AviatorObject.bitAnd

**Comment by NewGr8Player** [comment]
> com.googlecode.aviator.runtime.type.AviatorObject.bitAnd

这个一般情况下是因为是使用了类似下面的表达式参与运算造成的
```Java
AviatorEvaluator.execute("(1==2) & (1==2);");
```

因为`AviatorBoolean`中没有实现`bitAnd`方法，默认使用了父类`AviatorObject`的`bitAnd`方法，父类中的实现如下：
https://github.com/killme2008/aviatorscript/blob/20a3c7f432446861da28a67d5fdee7d959fcc05c/src/main/java/com/googlecode/aviator/runtime/type/AviatorObject.java#L157-L160
参考以下两个文件
- src/main/java/com/googlecode/aviator/runtime/type/AviatorBoolean.java
- src/main/java/com/googlecode/aviator/runtime/type/AviatorObject.java

**Comment by 18206872076** [comment]
您说的这种情况我大致清楚了， 我的困惑是这种场景不是必现的， 是偶发的性的， 而且是在并发较大的时候。

**Comment by 18206872076** [comment]
@killme2008 您说的这种情况我大致清楚了， 我的困惑是这种场景不是必现的， 是偶发的性的， 而且是在并发较大的时候。

**Comment by killme2008** [comment]
这跟表达式本身的并发执行没有关系，很可能是你的 aviator evaluator instance 有多个，有的配置正确，有的配置不正确。

**Comment by 18206872076** [comment]
感谢回复，问题的原因已经找到了，我们自己对操作符做了重载， 但是服务有多个节点，其中一个节点在重启过程中接受了请求，此时符号重载注册的还未完成，导致执行了引擎默认的运算逻辑 ， 执行之后即被引擎缓存 ，而引擎本身没有支持bitAnd运算 ， 所以出现了部分节点报错，部分节点不报错的情况。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "killme2008/aviatorscript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月3日(星期二) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [killme2008/aviatorscript] 请问下什么场景下会出现这个报错呢 Could not bitAnd <Boolean, false&gt; with <Boolean, false&gt; ？ (Issue #558)





 
这跟表达式本身的并发执行没有关系，很可能是你的 aviator evaluator instance 有多个，有的配置正确，有的配置不正确。
