### ISSUE TITLE
表达式引用插值（或复用）

### ISSUE THREAD

**Issue by deific** [killme2008/aviatorscript#559]
场景：当有多个表达式时，b表达式依赖a表达式的值，是否支持？
例子：
a表达式(计算费率）：` if (amount > 100) { 10 } else {20}；`
b表达式(费率分析）：`if（$a > 20) { error("费率过高") } else { info("正常")}`

a表达式是根据amount计算费率的表达式，b表达式引用a表达式的结果，对其结果做自己的表达式计算。
目前想到的方法：
1、当计算b表达式时，查看b表达式里的变量，发现是$开头的，以变量a作为key，查找a对应的表达式（事先缓存），求值后作为b表达式的参数传入。
2、修改a表达式，将其逻辑封装为函数模块，导出后供a和b使用，这种方式对a的改动较大。

想问是否还有别的方法，原生里面是否能够支持？

**Comment by killme2008** [comment]
这是应用设计的问题，个人觉的两者都可以，更偏向1.

原生的话就是支持模块系统，可以将 a 封装为模块，其他模块调用

https://www.yuque.com/boyan-avfmj/aviatorscript/rqra81
