### ISSUE TITLE
5.2.7版本 if...elsif... 和 continue 组合使用 end未打印

### ISSUE THREAD

**Issue by zzw159263** [killme2008/aviatorscript#566]
for i in range(0, 10) {

    if (i != 3 && i != 2) {
        log("condition1");
    } elsif(i != 3) {
        log("condition2");
    } elsif(i != 2) {
        log("condition3");
        continue;
    }
    
    log("end"+i)
}

**Comment by zzw159263** [comment]
分析下边的代码的结果，好像是每个if分支条件都加上了continue
for i in range(0, 10) {

    if (i == 1) {
        log("condition1");
    } elsif(i == 2) {
        log("condition2");
    } elsif(i == 3) {
        log("condition3");
        continue;
    }
    
    log("end"+i)
}

**Comment by killme2008** [comment]
应该是跟这个一样的问题 https://github.com/killme2008/aviatorscript/issues/554 
近期会修复，感谢报告

**Comment by killme2008** [comment]
Fixed in v5.4.0 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.0
