### ISSUE TITLE
是否考虑开启trace后不让短路失效

### ISSUE THREAD

**Issue by 1sua** [killme2008/aviatorscript#569]
现阶段开启trace 后，短路失效，直接报错，不能很好的排查代码错误

**Comment by Topcoder2023** [comment]
同上，不仅在开启 trace 后，添加了自定义操作符后也会是短路失效，看源码应该和生成的ASM字节码调用逻辑顺序有关

**Comment by killme2008** [comment]
开启 trace 后就需要跟踪所有参数的结果，所以会先对参数求值，然后再执行对应的操作符。
