### ISSUE TITLE
是否可以进行“自动将传入的null值转换成0”的操作

### ISSUE THREAD

**Issue by zhaocannan** [killme2008/aviatorscript#573]
在我的代码中,将可能会用的到的所有值一股脑放进了env中,但是还是会不可避免的出现找不到的情况,想咨询一下是否有标题中的这种配置(不会影响我的计算),不然处理空值太头疼了,谢谢

**Comment by killme2008** [comment]
可以使用 `EnvProcessor` 做前置和后置处理

https://github.com/killme2008/aviatorscript/blob/master/src/main/java/com/googlecode/aviator/EnvProcessor.java

https://github.com/killme2008/aviatorscript/blob/976911d039f259ea23bb41fa61c91c4305c2ad4f/src/main/java/com/googlecode/aviator/AviatorEvaluatorInstance.java#L306
