### ISSUE TITLE
LongFunction存在NPE问题

### ISSUE THREAD

**Issue by nkbaixiaojie** [killme2008/aviatorscript#591]
com.googlecode.aviator.runtime.function.system.LogFunction类中：

若obj的值为null，则下方代码中的obj.getClass()会抛NPE异常
throw new ClassCastException("Could not cast " + obj.getClass().getName() + " to long");

![image](https://github.com/killme2008/aviatorscript/assets/416373/f1de13be-fae1-4b95-8d7c-c43117dc6b66)

**Comment by killme2008** [comment]
Good catch，欢迎提个修复 PR

**Comment by killme2008** [comment]
Fixed via https://github.com/killme2008/aviatorscript/pull/615
