### ISSUE TITLE
语雀里面关于序列化的文档能补充一下吗

### ISSUE THREAD

**Issue by andy-yanggu** [killme2008/aviatorscript#596]
[11.高阶主题：序列化等](https://www.yuque.com/boyan-avfmj/aviatorscript/gn553diuot5ckra2)

**Comment by andy-yanggu** [comment]
页面打开的是404，啥也没有
![image](https://github.com/killme2008/aviatorscript/assets/69521061/d69f2b7d-dc4e-427d-8db3-14e46b2f5a92)

**Comment by killme2008** [comment]
谢谢反馈，是语雀默认创建的是私有文档了，我刚开放了。
