### ISSUE TITLE
使用use导入后getVariableFullNames不符合预期

### ISSUE THREAD

**Issue by cyningchen** [killme2008/aviatorscript#597]
use java.lang.Thread;
Thread.sleep(2000);
return 1 > 0;

期望的variables: []
实际的variables: ["java.lang.Thread"]

**Comment by killme2008** [comment]
Good catch! 下个版本修复。

**Comment by killme2008** [comment]
v5.4.2 release https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.2
