### ISSUE TITLE
表达式根据上下文自适应

### ISSUE THREAD

**Issue by charlesmiao** [killme2008/aviatorscript#598]
比如设置一些表达式 A=A1+A2+A3， 当上下文获取到 [A1:3,A2:4],未获取到 A3的值，期望 A=A1+A2=3+4， 但实际结果变成A=3+4+A3，导致计算异常。

实际需求场景还有： 
1+ A3[上下文不存在的变量] , 期望 得到 1； 
1/ A3[上下文不存在的变量] , 期望 得到 null； 
1*A3[上下文不存在的变量] , 期望 得到 null； 

由于表达式是前端配置的，一个一个判断非常麻烦，请问有什么好的方法解决此类计算的问题？

**Comment by andy-yanggu** [comment]
在编写表达式时，自行处理没有值的情况，或者给默认值

**Comment by charlesmiao** [comment]
比如表达式 “A+B”，A, B默认值都是0， 表达式应该如何编写，才能别aviactor识别呢。
