### ISSUE TITLE
使用"<"，">"等比较类表达式参数不存在直接计算true问题

### ISSUE THREAD

**Issue by tech-jum** [killme2008/aviatorscript#601]
如下面的表达式计算:
    public void ruleValidatorTest1()throws Exception  {
        String expr = "test<10";
        Map<String, Object> context = ImmutableMap.of("test1", (Object) 10);
        Object o  = AviatorEvaluator.execute(expr, context);
        System.out.println(o);
    }
找不到参数替换的时候计算为true

**Comment by killme2008** [comment]
老问题，请认真阅读文档或者搜索 issue。nil 比任何值都小，除了它本身。
