### ISSUE TITLE
Compile能否提前发现某些Function不可用？

### ISSUE THREAD

**Issue by fjdingsd** [killme2008/aviatorscript#609]
使用 disableFeature 或 removeFunction 的时候，只能是在 execute 后才能报错 “xxx not found”
能否在compile时就能发现？
这种行为更像是解释型？
更有点不解5.3之后的编译和解释两种模式了

**Comment by killme2008** [comment]
v5.4.2 release https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.2
