### ISSUE TITLE
版本4.2.5 jdk版本openjdk11

### ISSUE THREAD

**Issue by mousans** [killme2008/aviatorscript#610]
编译expression类时，版本4.2.5 aviatorscript会默认先加载为匿名类，但我们跟踪aviator的编译类代码发现，在加载匿名类时，永远失败，导致最终都使用传入loaderclass加载类，导致这些被加载的脚本类无法卸载
<img width="1159" alt="image" src="https://github.com/killme2008/aviatorscript/assets/37068792/02ac554d-f503-4e57-9bc2-fcbdc6f6d382">

**Comment by killme2008** [comment]
不再维护，建议升级
