### ISSUE TITLE
context污染的问题

### ISSUE THREAD

**Issue by lonelystone545** [killme2008/aviatorscript#618]
在执行一个表达上时，如果表达式比较复杂，且有中间变量的定义，那么最终输出结果的同时，会把中间变量的值也放在context中，直接污染了业务系统传进去的context了。aviator底层在执行的时候，也不应该去污染业务系统传进去的context呢？
比如context={name=xiaoming}
执行表达式：let a=name; return name.test.result;
输出结果的同时，context变成如下：{"a":"xiaoming","test":{},"name":"xiaoming"}，多了"a"和"test"

**Comment by killme2008** [comment]
设置 `USE_USER_ENV_AS_TOP_ENV_DIRECTLY` 为 `false` 即可。

https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#USE_USER_ENV_AS_TOP_ENV_DIRECTLY
