### ISSUE TITLE
com.googlecode.aviator.runtime.function.FunctionUtils 方法报错问题

### ISSUE THREAD

**Issue by zimingFan** [killme2008/aviatorscript#619]
![Uploading 捕获.PNG…]()
此段代码如果输出的结果是非 String 类型 的数据会报错，因为无法强转，建议改为

  /**
   * Get string value from env.
   *
   * @param arg the var name
   * @param env
   * @return
   */
  public static final String getStringValue(final AviatorObject arg,
      final Map<String, Object> env) {
     final Object value = arg.getValue(env);
    if(value != null){
     return value.toString();
    }
   return null;
  }

**Comment by zimingFan** [comment]
当然详细的内容我并没有测试,这个例子并不知道会产生什么后果,,仅供参考

**Comment by killme2008** [comment]
这个方法就是假设你传入的参数是字符串，如果不是，请自己明确去转换，比如自己实现一个 `to_string` 方法。
隐式转换带来的 bug 将很难查。
