### ISSUE TITLE
输入错误aviator表达式导致metaspace oom

### ISSUE THREAD

**Issue by Leeforrest** [killme2008/aviatorscript#621]
我使用的是5.1.4版本，因为配置错了表达式，导致虽然开启了cache，但是每次依然需要newCodeGenerator，最终导致系统metaspace oom。
分析内存后发现大量的script类，
<img width="1525" alt="image" src="https://github.com/killme2008/aviatorscript/assets/6914757/849be15a-a403-4d00-a80c-74b4862b8a18">
想请教下是否是这个原因导致oom？
另外想请教下这个在5.3.3已经修复了这个问题吗？

**Comment by killme2008** [comment]
版本太老了，不确定了，建议升级。

**Comment by gunbi** [comment]
碰到了同样的问题，最新版本(5.4.1)。排查下来是因为语法错误的Script会一直生成AviatorScript_对象导致的OOM（开启cache也没有用）
![image](https://github.com/killme2008/aviatorscript/assets/49774134/3e56ba22-d7e7-4447-87c3-588368759d97)
代码中：

执行代码：
<img width="565" alt="image" src="https://github.com/killme2008/aviatorscript/assets/49774134/bbf973ab-e3db-4c96-b07e-e6c079167eb1">

分析：
<img width="733" alt="image" src="https://github.com/killme2008/aviatorscript/assets/49774134/616df821-c6b1-494e-b3d6-4dca22567add">
<img width="820" alt="image" src="https://github.com/killme2008/aviatorscript/assets/49774134/8240a7fb-6404-4c5a-a87c-0ffed7e9df71">

1. innerCompile方法中parser.parse();抛出异常
2. 从cache中将对应的Task移除了。

在parser.parse();之前: 
CodeGenerator codeGenerator = newCodeGenerator(sourceFile, cached); =>
new ASMCodeGenerator(this, sourceFile, classLoader, this.traceOutputStream);
=> JVM visit class完成 => metaspace中存在:"AviatorScript_"class

如果大量的语法错误的Script执行会导致OOM。


现有的解决方案是在执行前调用 validate 方法，因为不会生成字节码对应的class
<img width="675" alt="image" src="https://github.com/killme2008/aviatorscript/assets/49774134/0380d64e-5239-4d18-908c-4a0c38b1ac40">

建议在compile方法中前置调用 validate方法，再进cache逻辑

**Comment by killme2008** [comment]
从 API 设计的角度， API 的功能最好是正交的，已经提供了 `validate` 方法来做一些提前校验，可以搭配 `compile` 和 `execute` 方法来试用。
