### ISSUE TITLE
编译表达式解析不出表达式的变量

### ISSUE THREAD

**Issue by yicold1204** [killme2008/aviatorscript#626]
环境：Java 8 ，avaitor版本：5.41
情况描述：我这边获取了AviatorEvaluatorInstance后，执行表达式“e1001+e1003”，方法直接在http接口中调用，能够正常解析出两个变量e1001和e1003，但是在消息队列中调用解析出来的变量名称是0，有时候关掉缓存又能用，但是第二天又不行了

![b5fe59abd8ff21385aef18d163a3c19](https://github.com/killme2008/aviatorscript/assets/170398506/d79a6286-0ef3-4f9f-a1a4-75372985ccfe)
![ccefa64c902a00c8329387719b7dc74](https://github.com/killme2008/aviatorscript/assets/170398506/02eeb36d-5690-4c0b-bba6-3c36754d966a)

**Comment by yicold1204** [comment]
补充一下，我在每次执行前，设置一下优化级别和浮点型解析就可以使用，每次执行都要设置，不然还是会报错，很奇怪，因为这个bean我在注入时就已经配置过了，注入bean时的配置和执行相关代码如下，也不知道现在是突然好了还是之后还会出现这个问题，求大佬指点一下
![image](https://github.com/killme2008/aviatorscript/assets/170398506/b7f89784-9dc6-4699-b2f4-cf60bd40c303)
![image](https://github.com/killme2008/aviatorscript/assets/170398506/ceac9d50-d44f-4eb4-8b3b-59b21700907f)

**Comment by killme2008** [comment]
检查你的 classpath 里是不是有多个 aviatorscirpt 版本依赖吧。

**Comment by jiangyunpeng** [comment]
> 检查你的 classpath 里是不是有多个 aviatorscirpt 版本依赖吧，大概率是这个问题

大佬，如果在 aviator 中增加一段检测代码，当发现classpath存在多个版本直接报错，这样做是否合适?

**Comment by killme2008** [comment]
这不是一个类库的职责
