### ISSUE TITLE
为啥每次执行都加载了一个莫名的类，导致java元空间一直增长，最后导致Fullgc

### ISSUE THREAD

**Issue by 534817545** [killme2008/aviatorscript#633]
项目中Fullgc频繁，发现元空间持续增长，启动类加上-verbose:class打印类加载详情， 排除下来发现每次请求都会加载下面这个莫名的类，请问大佬们有啥方法可以跳过这个步骤？
[Loaded AviatorScript_1718850062114_7034/1769008551 from com.googlecode.aviator.Expression]

这是dump下来的内存快照，发现很多这样的脚本，这是无法避免的吗？
![1718850188060](https://github.com/killme2008/aviatorscript/assets/44426624/f66962d2-7832-4e21-9fd3-de6c9746be35)

**Comment by killme2008** [comment]
请阅读文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy
