### ISSUE TITLE
JAVA 代码中的 上下文数据，怎么在自定义函数中使用

### ISSUE THREAD

**Issue by xiexingguang** [killme2008/aviatorscript#645]
例子：
java 代码：
//java 代码中的context
Map<String,Object>  context 

//执行aviator脚本。脚本希望从前面的context 获取数据, 然后将处理的数据在塞回给java 代码中的context

**Comment by killme2008** [comment]
把 context 作为 env 传入，并且设置 `Opitons.USE_USER_ENV_AS_TOP_ENV_DIRECTLY` 为 `true`

https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#USE_USER_ENV_AS_TOP_ENV_DIRECTLY

当然，你其实可以将 env 简单的传回去，在脚本最后增加 `return __env__;` 即可。
