### ISSUE TITLE
传递上下文信息

### ISSUE THREAD

**Issue by hackerpayne** [killme2008/aviatorscript#651]
求助，希望在执行多个逻辑时，后面的逻辑能传递上下文信息。比如：

a = filter(p.fee,'aaa');
b = filter(a,'bbb');
c = filter(b,'ccc');
d = filter(c,'ddd');
return contains(c,'abcd') && p.day > 9;

希望在contains中，能知道上一步是filter函数，参数是c和abcd。

目前在自定义函数中，使用了FunctionResult实体类将结果一层一层传递。

但是到最后一步的时候contains返回的也是FunctionResult无法和 p.day>9这种进行计算。

**Comment by killme2008** [comment]
这样的需求请自行解决，也许应该分析下是否合理，或者有没有其他的解决办法。
